const fs=require('fs');
const D=require('/opt/node-tools/node_modules/docx');
const {Document,Packer,Paragraph,TextRun,Table,TableRow,TableCell,AlignmentType,BorderStyle,WidthType,ShadingType,LevelFormat,VerticalAlign,Footer,PageNumber,ImageRun}=D;
const NAVY='1F3864',BLUE='2E75B6';
function runs(t,o={}){ // **bold**, *italic*
  const out=[];
  t.split('**').forEach((seg,i)=>{ seg.split('*').forEach((s2,j)=>{ if(s2==='') return; out.push(new TextRun({text:s2,bold:(i%2===1)||o.bold,italics:(j%2===1)||o.italics,size:o.size||24,color:o.color,font:'Arial'})); }); });
  return out;
}
const body=(t)=>new Paragraph({alignment:AlignmentType.JUSTIFIED,spacing:{line:360,lineRule:'auto',before:0,after:160},indent:{firstLine:709},children:runs(t)});
const plain=(t,o={})=>new Paragraph({alignment:o.align||AlignmentType.JUSTIFIED,spacing:{line:360,before:0,after:o.after??160},indent:o.indent||{},children:runs(t,o)});
const H1=(t)=>new Paragraph({keepNext:true,spacing:{before:320,after:140,line:276},indent:{},border:{bottom:{style:BorderStyle.SINGLE,size:6,color:BLUE,space:1}},children:[new TextRun({text:t.toUpperCase(),bold:true,color:NAVY,size:24,font:'Arial'})]});
const H2=(t)=>new Paragraph({keepNext:true,spacing:{before:280,after:120,line:276},indent:{},children:[new TextRun({text:t.toUpperCase(),bold:true,color:NAVY,size:24,font:'Arial'})]});
const cons=(t)=>new Paragraph({alignment:AlignmentType.JUSTIFIED,spacing:{line:360,before:0,after:160},indent:{firstLine:709},children:[new TextRun({text:'Consequência processual: ',size:24,font:'Arial'}),...runs(t)]});
const Esp=(h)=>new Paragraph({spacing:{before:0,after:h},children:[]});
const bd={style:BorderStyle.SINGLE,size:1,color:'BECFE0'};const B={top:bd,bottom:bd,left:bd,right:bd};
function table(widths,head,rows,opt={}){
  const mk=(txt,w,fill,bold,al)=>new TableCell({width:{size:w,type:WidthType.DXA},borders:B,verticalAlign:VerticalAlign.CENTER,shading:{type:ShadingType.CLEAR,color:'auto',fill},margins:{top:70,bottom:70,left:110,right:110},children:[new Paragraph({alignment:al||AlignmentType.LEFT,spacing:{line:240,before:0,after:0},children:runs(String(txt),{size:20,bold,color:bold&&fill==='F0F4F8'?NAVY:undefined})})]});
  const tr=[new TableRow({tableHeader:true,cantSplit:true,children:head.map((h,i)=>mk(h,widths[i],'F0F4F8',true))})];
  rows.forEach((r,ri)=>tr.push(new TableRow({cantSplit:true,children:r.map((c,i)=>mk(c,widths[i],ri%2?'F7F9FB':'FFFFFF',false,(opt.right&&opt.right.includes(i))?AlignmentType.RIGHT:AlignmentType.LEFT))})));
  return new Table({width:{size:widths.reduce((a,b)=>a+b,0),type:WidthType.DXA},columnWidths:widths,rows:tr});
}
const legend=(t)=>new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:80,after:200,line:240},children:[new TextRun({text:t,italics:true,size:20,font:'Arial'})]});
const alinea=(t)=>new Paragraph({alignment:AlignmentType.JUSTIFIED,spacing:{line:360,before:0,after:120},indent:{left:709,hanging:425},children:runs(t)});
const C=[];
const ID='Processo nº 0003504-56.2026.8.05.0141';
const fig=(file,w,h,cap)=>[new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:80,after:60},children:[new ImageRun({type:'png',data:fs.readFileSync(file),transformation:{width:w,height:h}})]}),legend(cap)];
C.push(new Paragraph({alignment:AlignmentType.JUSTIFIED,spacing:{after:160,line:276},children:[new TextRun({text:'AO JUÍZO DA 1ª VARA DO SISTEMA DOS JUIZADOS ESPECIAIS DA COMARCA DE JEQUIÉ — BAHIA',bold:true,size:24,font:'Arial'})]}));
C.push(new Paragraph({border:{bottom:{style:BorderStyle.SINGLE,size:3,color:'CCCCCC',space:1}},spacing:{after:160},children:[]}));
['**'+ID+'**','**Recorrente:** LUCAS SOUZA CHAVES','**Recorrido:** BANCO C6 S.A. (polo passivo retificado na sentença)'].forEach(t=>C.push(plain(t,{after:60,align:AlignmentType.LEFT})));
C.push(Esp(200));
C.push(new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:80},children:[new TextRun({text:'RECURSO INOMINADO',bold:true,color:NAVY,size:30,font:'Arial'})]}));
C.push(new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:240},children:[new TextRun({text:'arts. 41 e 42 da Lei 9.099/95 — com pedido de gratuidade da justiça e de arbitramento de danos morais',italics:true,size:22,font:'Arial'})]}));
C.push(new Paragraph({border:{bottom:{style:BorderStyle.SINGLE,size:6,color:NAVY,space:1}},spacing:{after:200},children:[]}));

C.push(H1('Parte A — Petição de interposição'));
C.push(body('**LUCAS SOUZA CHAVES**, já qualificado nos autos da ação declaratória de inexistência de relação jurídica c/c obrigação de fazer e indenização por danos morais que move em face de **BANCO C6 S.A.**, vem, **tempestivamente**, com fundamento no **art. 41 da Lei nº 9.099/95**, interpor **RECURSO INOMINADO** contra a r. sentença de Id. 206519757 (Págs. 203–207), que julgou improcedentes os pedidos, pelas razões anexas, que requer sejam recebidas e processadas.'));
C.push(body('**Tempestividade.** O Recorrente foi intimado da sentença em **30/09/2026** [VERIFICAR ANTES DE PROTOCOLAR a data exata]; o prazo é de 10 (dez) dias úteis (art. 42 da Lei 9.099/95 c/c art. 219 do CPC e Enunciado 165 do FONAJE), de modo que o recurso é tempestivo.'));
C.push(body('**Preparo e gratuidade.** A gratuidade foi requerida na inicial e impugnada pelo Recorrido (Id. 205646946, Págs. 94–95). A sentença deixou de apreciá-la, consignando que, "em caso de interposição de recurso, os requisitos serão apreciados" (Id. 206519757, Pág. 203). O pedido é **renovado** e instruído com a **Carteira de Trabalho Digital do Recorrente (Doc. 1)**, conforme o tópico II.2 das razões. Requer-se a dispensa do preparo (art. 42, § 1º, da Lei 9.099/95 c/c arts. 98 e 99, § 7º, do CPC [VERIFICAR ANTES DE PROTOCOLAR]) e, apenas por cautela e sem prejuízo do pedido, que, em caso de indeferimento, seja fixado prazo para recolhimento, evitando-se a deserção.'));
C.push(body('Requer, ao final, o recebimento do recurso, a intimação do Recorrido para contrarrazões e a remessa à Egrégia Turma Recursal.'));
C.push(plain('Nestes termos, pede deferimento.',{align:AlignmentType.LEFT,indent:{firstLine:708},after:60}));
C.push(plain('Jequié/BA, ___ de outubro de 2026.',{align:AlignmentType.LEFT,indent:{firstLine:708},after:200}));
C.push(plain('CLEYTON DA SILVA BARBOSA',{align:AlignmentType.CENTER,after:0,bold:true}));
C.push(plain('OAB/MS 17.311 — OAB/BA 92.148',{align:AlignmentType.CENTER,after:300}));

C.push(new Paragraph({pageBreakBefore:true,alignment:AlignmentType.JUSTIFIED,spacing:{after:160,line:276},children:[new TextRun({text:'EGRÉGIA TURMA RECURSAL DOS JUIZADOS ESPECIAIS CÍVEIS E CRIMINAIS DO ESTADO DA BAHIA',bold:true,size:24,font:'Arial'})]}));
['**Recurso Inominado — '+ID+'** (origem: 1ª Vara do Sistema dos Juizados de Jequié/BA)','**Recorrente:** LUCAS SOUZA CHAVES','**Recorrido:** BANCO C6 S.A.'].forEach(t=>C.push(plain(t,{after:60,align:AlignmentType.LEFT})));
C.push(H1('Parte B — Razões do recurso inominado'));
C.push(plain('**Colenda Turma, Eméritos Julgadores,**',{align:AlignmentType.LEFT,after:160}));

C.push(H2('I — Síntese da demanda e da sentença recorrida'));
C.push(body('O Recorrente consultou o Registrato do Banco Central e constatou relacionamento em seu nome com o Banco C6 S.A., iniciado em **27/09/2021** (Id. 202248017), que afirma não ter solicitado nem contratado. Ajuizou ação declaratória c/c obrigação de fazer e indenização por danos morais (R$ 8.000,00) e por desvio produtivo (R$ 2.000,00).'));
C.push(body('A sentença julgou improcedentes todos os pedidos. Admitiu a inversão do ônus da prova e reconheceu que "à instituição financeira incumbia demonstrar a regularidade da abertura da conta e a existência de elementos capazes de vincular o autor à contratação impugnada", mas entendeu que a Recorrida "se desincumbiu satisfatoriamente" desse encargo porque a contestação "não veio acompanhada apenas de telas cadastrais", mas de "fotografia obtida mediante biometria facial e imagem do documento de identificação utilizado na contratação, além dos respectivos dados cadastrais", e porque o endereço do cadastro coincide com o da inicial (Id. 206519757, Pág. 204). Considerou ainda que, em depoimento, o Recorrente reconheceu sua fotografia e "não afirmou categoricamente jamais ter solicitado a abertura da conta" (Pág. 205).'));
C.push(body('**A *ratio decidendi* atacada:** o Juízo reputou provada a contratação por **três imagens e uma tabela de dados, todas coladas no corpo da própria contestação**, sem contrato, sem proposta, sem aceite e sem registro técnico da sessão de abertura, e converteu o reconhecimento, pelo Recorrente, de **sua própria imagem** em prova de que **foi ele quem abriu a conta**.'));

C.push(H2('II — Admissibilidade'));
C.push(H2('II.1 — Cabimento, tempestividade e interesse'));
C.push(body('O recurso é cabível (art. 41 da Lei 9.099/95), foi interposto no prazo de 10 dias úteis (art. 42) e o Recorrente tem interesse, pois teve todos os pedidos julgados improcedentes.'));
C.push(H2('II.2 — Gratuidade da justiça: comprovação pela CTPS'));
C.push(body('O Recorrente declarou, sob as penas da lei, não poder arcar com as despesas do processo sem prejuízo do próprio sustento. A declaração de pessoa natural presume-se verdadeira (art. 99, § 3º, do CPC), e o benefício só pode ser indeferido se houver nos autos elementos que evidenciem a falta dos pressupostos, após intimação da parte para comprová-los (art. 99, § 2º). O Recorrido impugnou a gratuidade (Id. 205646946, Págs. 94–95) com argumentação genérica, **sem apontar um único elemento concreto** de capacidade econômica do Recorrente: não indicou renda, patrimônio nem despesa; limitou-se a sustentar que o benefício seria "restrito". Pelo contrário, a **Carteira de Trabalho Digital (Doc. 1)**, assinada digitalmente pela Dataprev em 29/07/2026, demonstra renda de subsistência:'));
C.push(table([3400,5626],['Dado da CTPS Digital (Doc. 1)','Informação'],[
['Vínculo atual','MACIVALDO SOUZA COELHO — Jequié/BA; cargo de **Estoquista** (CBO 4141-05); contrato por prazo indeterminado; **admissão em 20/01/2021**; vínculo em aberto ("a (atual)")'],
['Remuneração atual','**R$ 1.653,00 por mês**, desde 01/04/2026 (R$ 1.621,00 desde 01/01/2026)'],
['Evolução salarial','R$ 1.100,00 (2021); R$ 1.240,00 (2022); R$ 1.350,00 (2023); R$ 1.451,00 (2024); R$ 1.550,00 (2025): reajustes anuais de pequena monta, sem mudança de cargo em mais de cinco anos'],
['Vínculos anteriores','Equipacar Peças e Tintas Ltda. — serviços gerais — 10/01/2020 a 05/12/2020 — R$ 552,00 a R$ 1.104,00'],
['Outros vínculos simultâneos','Nenhum registrado'],
]));
C.push(legend('Quadro 1 — Renda do Recorrente segundo a CTPS Digital (Doc. 1)'));
C.push(body('A renda registrada é de **R$ 1.653,00 mensais**, pouco acima de um salário mínimo (R$ 1.621,00 em 2026), em cargo operacional ocupado há mais de cinco anos e sem outro vínculo. É renda de subsistência, que não comporta o desembolso de preparo recursal sem prejuízo do sustento (art. 5º, LXXIV, da CF/88; art. 98 do CPC). Requer-se a **concessão da gratuidade**, com dispensa do preparo (art. 99, § 7º, do CPC [VERIFICAR ANTES DE PROTOCOLAR]); se o Colegiado entender necessária prova complementar (contracheque, declaração de imposto de renda, despesas ordinárias), requer-se **intimação prévia para complementação** (art. 99, § 2º) e, em último caso, prazo para recolhimento, sem deserção. A gratuidade suspende, ainda, a exigibilidade de eventual sucumbência recursal (art. 98, § 3º, do CPC [VERIFICAR ANTES DE PROTOCOLAR]).'));

C.push(H2('III — Delimitação do objeto e mapa dos fundamentos da sentença'));
C.push(body('Como a sentença é de **improcedência total**, devolve-se à Turma o capítulo integral: o mérito da contratação, o encerramento da conta e as indenizações.'));
C.push(table([480,3500,2400,2646],['#','Fundamento da sentença (Id. 206519757)','Erro apontado','Atacado em'],[
['1','A Recorrida "se desincumbiu satisfatoriamente": fotografia de biometria, imagem do documento e dados cadastrais (Pág. 204)','Erro de fato: elementos colados na contestação, sem origem, data, sessão ou instrumento','IV.1 e IV.2'],
['2','Silêncio sobre a ausência de contrato individualizado, aceite e assinatura (argumento da réplica, item VI)','Omissão: o "contrato" juntado é formulário-padrão, sem nome, aceite ou assinatura','IV.3'],
['3','Depoimento: reconheceu a fotografia; "não afirmou categoricamente" que nunca solicitou a conta (Pág. 205)','Erro de direito: reconhecer a própria imagem não é confessar a contratação; ônus segue com a Recorrida','IV.4'],
['4','A ausência de IP, dispositivo e geolocalização "não implica, por si só, invalidade" (Pág. 206)','Erro de direito: sob inversão, a lacuna da prova pesa contra quem a detém','IV.2'],
['5','Sem uso da conta, sem negativação: sem dano; desvio produtivo não provado (Pág. 206)','Erro de direito: dano presumido; uso da conta não é requisito','IV.5'],
]));
C.push(legend('Quadro 2 — Fundamentos da sentença, erros e seções de ataque'));

C.push(H2('IV — Razões de reforma'));
C.push(H2('IV.1 — A prova da Recorrida não demonstra a origem do vínculo'));
C.push(body('A sentença acolheu corretamente que a inversão do ônus da prova se impõe e que cabia à Recorrida provar "a regularidade da abertura da conta e a existência de elementos capazes de vincular o autor à contratação". O erro está em considerar cumprido esse encargo. **Vincular o autor à contratação é demonstrar a origem do vínculo:** quem, quando, por qual canal, em que sessão e mediante que ato de vontade a conta foi aberta no Banco C6 em 27/09/2021. Nada disso foi demonstrado.'));
C.push(body('O que a Recorrida apresentou, no corpo da própria contestação (Id. 205646946, Págs. 97–98), foi: (a) um recorte rotulado "Foto Onboarding"; (b) duas imagens rotuladas "RG (Frente)" e "RG (Verso)"; (c) uma tabela de "Validação Cadastral". São **capturas coladas na peça de defesa**, redigida por advogados, **e não documentos extraídos do sistema**: não trazem data e hora da captura, identificação da sessão, endereço IP, modelo ou identificador do aparelho (a tabela exibe apenas um código de "Device Fingerprint"), nem arquivo original com metadados. O próprio Juízo registrou a falha: "a própria documentação registra falha na captura da geolocalização" (Id. 206519757, Pág. 206).'));
C.push(...fig('fig1_onboarding.png',470,165,'Figura 1 — "Foto Onboarding" e imagens do RG, como coladas na contestação (Id. 205646946, Pág. 97). Sem data, hora, sessão ou metadados; as imagens do RG não permitem a leitura de seus dados'));
C.push(...fig('fig2_validacao.png',470,202,'Figura 2 — "Validação Cadastral" (Id. 205646946, Pág. 98): "Geolocalização capturada (device)": "–"; "Distância device — endereço": "Falha na captura"'));
C.push(body('Telas, capturas e tabelas podem ter sido extraídas de **qualquer origem**: de outro cadastro do mesmo consumidor, de outro aplicativo, de redes sociais ou de bases de dados vazadas, e coladas em qualquer peça. Elas só têm valor probatório quando se demonstra a **cadeia de origem**: o arquivo original, a sessão que o produziu, o registro técnico do ato e a vinculação do ato a quem se atribui o consentimento. **Essa cadeia não existe nos autos.** A tabela de "Validação Cadastral" apenas informa que dados de bureau são "compatíveis"; **nome, CPF, data de nascimento, endereço, telefone e e-mail são justamente os dados obtidos em vazamentos** e usados para dar aparência de regularidade, e a "compatibilidade" não prova que foi o titular quem os digitou. A coincidência do endereço, que a sentença destaca, é de logradouro e cidade, dado de fácil obtenção, e não supre a ausência de geolocalização e de registro da sessão.'));
C.push(body('A Recorrida invoca "biometria facial" e "prova de vida", e transcreve precedente do STJ sobre a biometria facial em tese (Id. 205646946, Págs. 102–103). Mas **não juntou relatório técnico algum** da biometria deste cadastro: motor utilizado, índice de correspondência, limiares, indicação de captura viva (*liveness*) e data/hora. Uma fotografia estática, sem esse relatório, prova um rosto, não que o rosto foi capturado ao vivo, no ato da abertura, pelo titular. Como as imagens estão coladas na contestação, sequer é possível aferir quando foram tiradas. Sob a inversão do ônus (art. 6º, VIII, do CDC), que a própria sentença reconheceu, **a ausência desses elementos pesa contra quem os detém**. A sentença admitiu que a Recorrida "poderia ter apresentado outros elementos técnicos, como IP, identificação do dispositivo, geolocalização integral da sessão ou relatório técnico mais detalhado da autenticação biométrica" (Pág. 206), mas afirmou que a ausência "não implica, por si só, invalidade" e que a prova deve ser apreciada em conjunto (art. 371 do CPC). O "conjunto", porém, **é composto de peças que não provam a origem do ato**; somar lacunas não as preenche.'));
C.push(cons('a Recorrida não demonstrou a origem do vínculo; as capturas coladas na contestação, sem metadados, sessão ou relatório técnico, não vinculam o Recorrente à contratação (art. 373, II, do CPC; art. 6º, VIII, do CDC; Súmula 479/STJ).'));

C.push(H2('IV.2 — As telas do sistema e a ausência de prova técnica da sessão'));
C.push(body('A sentença já afastou, com acerto, as telas genéricas de tutorial (Págs. 99–101 da contestação), que exibem endereço no Rio de Janeiro, e-mail "teste@..." e telefone fictício, e concluiu que "servem, quando muito, à demonstração do funcionamento abstrato do procedimento". **O mesmo raciocínio deve alcançar as demais capturas.** A Recorrida sustenta que suas telas "reproduzem, de forma fidedigna, as informações contidas no sistema" e que "têm sido aceitas pelo judiciário como meios de prova" (Id. 205646946, Págs. 106–107). Mas o art. 425, V, do CPC confere valor às reproduções digitais **atestadas pelo emitente como correspondentes ao caso concreto**; tela colada em petição não é atestado, e a própria Recorrida mistura, nas mesmas páginas, telas genéricas (sem dado real) e telas individualizadas, sem identificar de qual sistema, data ou usuário foram extraídas. Um documento só prova o que se demonstra ser, e **nenhum dos elementos individualizados foi extraído com prova de autoria e integridade**.'));
C.push(body('A autenticação eletrônica de adesão a serviço financeiro exige elementos que permitam atribuir o ato à pessoa (MP 2.200-2/2001, art. 10, § 2º; Lei 14.063/2020), e as normas do Banco Central impõem às instituições "procedimentos e controles destinados à verificação e validação da identidade" e "requisitos de integridade, autenticidade e proteção das informações e documentos eletrônicos" (Res. CMN 4.753/2019, citada na sentença, Pág. 205). Cumprir tais deveres e **poder prová-lo** é encargo da instituição. Não há, nos autos, nenhum registro eletrônico do ato de abertura que permita a verificação dessa integridade.'));
C.push(cons('as capturas colocadas na contestação não são prova da sessão de abertura, e a lacuna probatória, sob inversão do ônus, opera contra a Recorrida.'));

C.push(H2('IV.3 — Não há contrato: o "contrato" juntado é formulário-padrão, sem identificação, aceite ou assinatura'));
C.push(body('A Recorrida juntou arquivo intitulado "CONTRATO CONTA CORRENTE – LUCAS SOUZA CHAVES" (Id. 205646947, Págs. 109–140). **O título é apenas o nome do arquivo.** O conteúdo é o "PROSPECTO / RESUMO DO CONTRATO DA SUA CONTA C6" e as condições gerais, redigidos em segunda pessoa ("**Você**"), com 32 páginas e rodapé de formulário ("OBD 1.C v14.20231018"). Do exame das páginas, inclusive da primeira (Pág. 109), de páginas intermediárias (Págs. 111, 124 e 134) e das duas últimas (Págs. 139 e 140, esta encerrada na cláusula 5.3 do serviço DDA), **não constam nome, CPF, número de conta, data de adesão, registro de aceite eletrônico, versão do termo aceita nem assinatura, física ou eletrônica, do Recorrente.** É texto-modelo da instituição, que remete o leitor ao seu sítio eletrônico para consulta das tarifas (Id. 205646947, Pág. 109, item 3).'));
C.push(body('Este foi o ponto que o Recorrente suscitou na réplica (item VI, Id. 205727612, Págs. 186–200): **a Recorrida não comprova ter sequer um instrumento contratual individualizado**, nem tela de aceite vinculada ao CPF, com data e hash, nem envio de cópia ao titular. **A sentença não o enfrentou**: nada diz sobre a natureza do documento nem sobre a ausência de aceite. Trata-se de argumento relevante, suscitado e discutido, que a sentença deveria ter apreciado (art. 489, § 1º, IV, do CPC [VERIFICAR ANTES DE PROTOCOLAR]); sua análise é devolvida a esta Turma, com profundidade de fato e direito (art. 1.013, §§ 1º e 2º, do CPC).'));
C.push(body('A falta de contrato é central porque **o contrato é o ato que origina o vínculo**. Sem proposta individualizada, aceite de termos e registro do ato (data, hora, IP, dispositivo, versão do documento aceita), nem mesmo se sabe qual a conta, em que condições e quando foi pactuada. **Aqui não há instrumento assinado nem aceite individualizado.** O precedente do TJBA que a Recorrida cita (Id. 205646946, Pág. 106) concerne a hipótese em que constavam "cópia do RG juntado e selfie tirada pelo próprio apelante", além de **faturas** e **uso** dos serviços pelo consumidor, circunstâncias que a sentença reconhece **não existirem aqui** (não houve uso, saque, empréstimo, nem movimentação identificada).'));
C.push(cons('não há contrato individualizado, proposta, aceite ou assinatura; a origem do vínculo é não provada, e a sentença não apreciou o argumento (art. 373, II, do CPC; art. 104 do CC).'));

C.push(H2('IV.4 — O depoimento: reconhecer a própria imagem não é confessar a contratação'));
C.push(body('A sentença deu peso decisivo ao depoimento pessoal do Recorrente, que "confirmou expressamente que a fotografia apresentada [...] como biometria facial é sua" (Pág. 205). Tal reconhecimento é verdadeiro e **sempre foi incontroverso**: a fotografia retrata o Recorrente (já na réplica o Recorrente reconheceu a compatibilidade da imagem; Id. 205727612). O erro está em tratar o reconhecimento da própria imagem como prova de que **o Recorrente a enviou ao banco para abrir a conta**. A imagem de uma pessoa pode ser obtida por terceiros por inúmeros meios, e **o fato admitido, "esta é minha fotografia", não é o fato que a Recorrida deveria provar, "fui eu quem contratou"** (cf. art. 389 do CPC [VERIFICAR ANTES DE PROTOCOLAR], que define a confissão pela admissão de fato contrário ao interesse do confitente e favorável ao adversário: o fato confessado aqui, a titularidade da imagem, não é o fato constitutivo da contratação).'));
C.push(body('O Recorrente **não confirmou ter contratado** a conta, e a sentença registra que "posteriormente nega a abertura da conta" (Pág. 205) [VERIFICAR ANTES DE PROTOCOLAR e indicar o minuto da gravação em que o Recorrente nega a abertura]. Que, inicialmente, "não se recordasse" de ter requerido conta aberta em 2021, há cinco anos, é compatível com a negativa. Mais: ao afirmar que "a afirmação de que não se recorda [...] não equivale à afirmação positiva de que o ato jamais ocorreu", a sentença **inverte o ônus que reconheceu pesar sobre a Recorrida**: não incumbia ao Recorrente negar "categoricamente" o ato (prova de fato negativo), mas à Recorrida prová-lo. Do mesmo modo, o fato de o Recorrente não possuir mais o documento de identidade que consta da imagem (Pág. 205) ou de não ter procurado o banco antes de ajuizar a ação, ponto que a própria sentença reconhece **não ser condição da ação**, não prova a contratação.'));
C.push(body('A sentença afirma, ainda, que "não há elemento objetivo indicativo de [...] utilização da conta por terceiro" (Pág. 206). A abertura de conta sem consentimento é o ilícito, e não depende de uso: contas abertas em nome de terceiros permanecem, não raro, dormentes até serem utilizadas. **A inatividade da conta não é prova de que o titular a abriu.**'));
C.push(cons('o reconhecimento da própria imagem não prova a contratação, e a sentença inverteu o ônus ao exigir negativa categórica do consumidor; reforma-se para declarar a inexistência da relação jurídica.'));

C.push(H2('IV.5 — Do dano moral, presumido na abertura de conta sem consentimento'));
C.push(body('Reconhecida a inexistência de contratação (tópicos IV.1 a IV.4), o dano é **presumido**. A sentença o afastou por não haver "cobrança indevida, inscrição em cadastro restritivo, contratação fraudulenta de empréstimo, saque, transferência ou redução patrimonial" (Pág. 206), mas tais fatos seriam danos **diversos e ulteriores**. A lesão aqui é a constituição, em nome do consumidor e à sua revelia, de relação financeira registrada no cadastro oficial do sistema financeiro, com o uso de seus dados pessoais (art. 5º, X e LXXIX, da CF/88; arts. 42 e 46 da LGPD), mantida desde 2021, sem que ele soubesse. A responsabilidade é objetiva (art. 14 do CDC; Súmula 479/STJ).'));
C.push(body('**Parâmetros.** (a) **REsp 2.201.694/SP (Doc. 2)**: a Terceira Turma do STJ, por maioria (Rel. p/ acórdão Min. Nancy Andrighi; j. 05/08/2025; DJEN 15/08/2025), assentou que o gestor de banco de dados que disponibiliza indevidamente dados do cadastrado "deve responder objetivamente pelos danos morais causados ao cadastrado, **que são presumidos, diante da forte sensação de insegurança por ele experimentada**" (ementa, item 4), e fixou **R$ 11.000,00**. O caso tem objeto próprio (birô de crédito) e é invocado como parâmetro do dano presumido por tratamento indevido de dados e da ordem de grandeza da compensação. (b) **Sentença no processo nº 0022386-55.2026.8.05.0080 (5ª VSJ de Feira de Santana/BA — Antonieta Freitas Mota × Dock Instituição de Pagamento S.A.) (Doc. 3)**: conta de pagamento aberta sem prova de contratação, sem negativação e sem prejuízo material alegado; a sentença, homologada pela Juíza de Direito, reconheceu "dano *in re ipsa*, decorrente da própria constituição e manutenção, à revelia da titular, de relacionamento inserido em cadastro oficial do sistema financeiro nacional", "dispensando-se a comprovação de prejuízo patrimonial específico", e fixou **R$ 5.000,00**. É decisão de primeiro grau, sem eficácia vinculante, trazida como parâmetro de razoabilidade em hipótese fática idêntica.'));
C.push(table([2900,2800,1500,1826],['Parâmetro','Natureza da lesão','Exigiu negativação?','Valor'],[
['REsp 2.201.694/SP (3ª T., STJ, 2025)','Dados pessoais disponibilizados indevidamente (dano presumido)','Não','R$ 11.000,00'],
['Proc. 0022386-55.2026.8.05.0080 (JEC Feira de Santana/BA, 2026)','Conta aberta sem prova de contratação, registrada no CCS (dano *in re ipsa*)','Não','R$ 5.000,00'],
['Pedido do Recorrente (inicial)','Conta aberta sem consentimento, ativa desde 27/09/2021','—','R$ 8.000,00 + R$ 2.000,00'],
]));
C.push(legend('Quadro 3 — Parâmetros de arbitramento'));
C.push(body('**Desvio produtivo.** A sentença o rejeitou porque o Recorrente não procurou o Recorrido antes da ação e não há prova de "sucessivas tentativas frustradas". Subsidiariamente, requer que o tempo despendido (requerimento administrativo juntado, Id. 203922033; audiência; acompanhamento do processo) seja considerado **na quantificação do dano moral**, como circunstância agravante (Súmula 30 da Turma Recursal do TJBA, invocada na inicial [VERIFICAR ANTES DE PROTOCOLAR a redação]).'));
C.push(body('**Arbitramento.** Os valores da inicial, **R$ 8.000,00** (danos morais) e **R$ 2.000,00** (desvio produtivo), totalizando **R$ 10.000,00**, situam-se **entre** os parâmetros do Quadro 3 e são mantidos. Caso a Turma não acolha os valores integrais, requer-se o **arbitramento pelo próprio Colegiado**, dentro do limite do pedido, em valor **não inferior a R$ 5.000,00**, com juros de mora desde o evento danoso (Súmula 54/STJ) ou, subsidiariamente, da citação, e correção monetária desde o arbitramento (Súmula 362/STJ), observado, para os períodos a partir de 30/08/2024, o art. 406 do CC, na redação da Lei 14.905/2024.'));
C.push(cons('constatada a ausência de contratação, o dano moral é presumido e independe do uso da conta; impõe-se a condenação e o arbitramento da indenização.'));

C.push(H2('V — Prequestionamento'));
C.push(body('Para fins de eventual Recurso Extraordinário (art. 102, III, da CF/88) e de pedido de uniformização de jurisprudência, ficam prequestionados os arts. 5º, X, XXXV, LXXIV e LXXIX, da CF/88; os arts. 6º, VIII, e 14 do CDC; a Súmula 479/STJ; os arts. 42 e 46 da Lei 13.709/2018; os arts. 373, 371, 425, V, e 489, § 1º, IV, do CPC; os arts. 98 e 99 do CPC; e a Res. CMN 4.753/2019. Registra-se a divergência, quanto ao dano presumido na abertura de conta sem prova de contratação e sem uso, entre a sentença de Feira de Santana/BA (Doc. 3), que o reconhece, e decisões que o negam, a justificar, se necessário, a uniformização.'));

C.push(H2('VI — Pedidos'));
C.push(body('Ante o exposto, requer o Recorrente:'));
[
'a)\tO **recebimento do recurso** com a **concessão da gratuidade da justiça**, dispensado o preparo (art. 42, § 1º, da Lei 9.099/95; arts. 98 e 99 do CPC), à vista da CTPS Digital (Doc. 1); subsidiariamente, a intimação para complementação da prova (art. 99, § 2º, do CPC) e, em último caso, prazo para recolhimento, sem deserção;',
'b)\tO **conhecimento e provimento do recurso** para reformar a sentença de Id. 206519757 e **declarar a inexistência da relação jurídica** relativa à conta aberta junto ao Banco C6 S.A. em 27/09/2021, por ausência de prova da origem do vínculo, de contrato individualizado, de aceite e de manifestação de vontade do titular;',
'c)\tA **determinação de encerramento definitivo da conta** e de exclusão do vínculo do CCS/Registrato, em prazo razoável e sob multa diária, ressalvada a guarda de dados exigida por lei;',
'd)\tA **condenação do Recorrido** ao pagamento de **R$ 8.000,00 a título de danos morais** e **R$ 2.000,00 a título de desvio produtivo**, valores da inicial, com juros e correção na forma do tópico IV.5;',
'e)\tSubsidiariamente, o **arbitramento judicial** dos danos morais pela Turma, em valor **não inferior a R$ 5.000,00**, dentro do limite do pedido, tomando-se por parâmetro o REsp 2.201.694/SP (R$ 11.000,00) e a sentença do processo nº 0022386-55.2026.8.05.0080 (R$ 5.000,00);',
'f)\tA manutenção da inversão do ônus da prova (art. 6º, VIII, do CDC; art. 373, § 1º, do CPC), reconhecida na sentença;',
'g)\tA ausência de condenação do Recorrente em custas e honorários, por ser beneficiário da gratuidade, e a condenação do Recorrido na sucumbência recursal, se vencido (art. 55 da Lei 9.099/95);',
'h)\tQue as intimações sejam feitas em nome do advogado **CLEYTON DA SILVA BARBOSA, OAB/MS 17.311 e OAB/BA 92.148**.'
].forEach(t=>C.push(alinea(t)));
C.push(plain('**Documentos anexos:** Doc. 1 — CTPS Digital do Recorrente (Dataprev, 29/07/2026); Doc. 2 — Acórdão do REsp 2.201.694/SP (STJ); Doc. 3 — Sentença do processo nº 0022386-55.2026.8.05.0080 (5ª VSJ de Feira de Santana/BA).',{align:AlignmentType.JUSTIFIED,after:200}));
C.push(plain('Nestes termos, pede deferimento.',{align:AlignmentType.LEFT,indent:{firstLine:708},after:60}));
C.push(plain('Jequié/BA, ___ de outubro de 2026.',{align:AlignmentType.LEFT,indent:{firstLine:708},after:400}));
C.push(plain('CLEYTON DA SILVA BARBOSA',{align:AlignmentType.CENTER,after:0,bold:true}));
C.push(plain('OAB/MS 17.311 — OAB/BA 92.148',{align:AlignmentType.CENTER,after:0}));
const doc=new Document({styles:{default:{document:{run:{font:'Arial',size:24}}}},
 sections:[{properties:{page:{size:{width:11906,height:16838},margin:{top:1701,bottom:1134,left:1701,right:1134}}},
 footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:ID+' — Recurso Inominado — página ',size:18,font:'Arial'}),new TextRun({children:[PageNumber.CURRENT],size:18,font:'Arial'}),new TextRun({text:' de ',size:18,font:'Arial'}),new TextRun({children:[PageNumber.TOTAL_PAGES],size:18,font:'Arial'})]})]})},
 children:C}]});
Packer.toBuffer(doc).then(b=>{fs.writeFileSync('recurso_inominado_conta_fraudulenta.docx',b);console.log('ok',b.length)});
