const fs=require('fs');
const D=require('/opt/node-tools/node_modules/docx');
const {Document,Packer,Paragraph,TextRun,Table,TableRow,TableCell,AlignmentType,BorderStyle,WidthType,ShadingType,LevelFormat,VerticalAlign,Footer,PageNumber,ImageRun}=D;
const NAVY='1F3864',BLUE='2E75B6';
function runs(t,o={}){ // **bold**, *italic*
  const out=[];
  t.split('**').forEach((seg,i)=>{ seg.split('*').forEach((s2,j)=>{ if(s2==='') return; out.push(new TextRun({text:s2,bold:(i%2===1)||o.bold,italics:(j%2===1)||o.italics,size:o.size||24,color:o.color,font:'Arial'})); }); });
  return out;
}
const body=(t)=>new Paragraph({alignment:AlignmentType.JUSTIFIED,spacing:{line:360,lineRule:'auto',before:0,after:160},indent:{firstLine:709},children:runs(t)});
const plain=(t,o={})=>new Paragraph({alignment:o.align||AlignmentType.JUSTIFIED,spacing:{line:360,before:0,after:o.after??160},indent:o.indent||{},children:runs(t,o)});
const H1=(t)=>new Paragraph({keepNext:true,spacing:{before:320,after:140,line:276},indent:{},border:{bottom:{style:BorderStyle.SINGLE,size:6,color:BLUE,space:1}},children:[new TextRun({text:t.toUpperCase(),bold:true,color:NAVY,size:24,font:'Arial'})]});
const H2=(t)=>new Paragraph({keepNext:true,spacing:{before:280,after:120,line:276},indent:{},children:[new TextRun({text:t.toUpperCase(),bold:true,color:NAVY,size:24,font:'Arial'})]});
const cons=(t)=>new Paragraph({alignment:AlignmentType.JUSTIFIED,spacing:{line:360,before:0,after:160},indent:{firstLine:709},children:[new TextRun({text:'Consequência processual: ',size:24,font:'Arial'}),...runs(t)]});
const Esp=(h)=>new Paragraph({spacing:{before:0,after:h},children:[]});
const bd={style:BorderStyle.SINGLE,size:1,color:'BECFE0'};const B={top:bd,bottom:bd,left:bd,right:bd};
function table(widths,head,rows,opt={}){
  const mk=(txt,w,fill,bold,al)=>new TableCell({width:{size:w,type:WidthType.DXA},borders:B,verticalAlign:VerticalAlign.CENTER,shading:{type:ShadingType.CLEAR,color:'auto',fill},margins:{top:70,bottom:70,left:110,right:110},children:[new Paragraph({alignment:al||AlignmentType.LEFT,spacing:{line:240,before:0,after:0},children:runs(String(txt),{size:20,bold,color:bold&&fill==='F0F4F8'?NAVY:undefined})})]});
  const tr=[new TableRow({tableHeader:true,cantSplit:true,children:head.map((h,i)=>mk(h,widths[i],'F0F4F8',true))})];
  rows.forEach((r,ri)=>tr.push(new TableRow({cantSplit:true,children:r.map((c,i)=>mk(c,widths[i],ri%2?'F7F9FB':'FFFFFF',false,(opt.right&&opt.right.includes(i))?AlignmentType.RIGHT:AlignmentType.LEFT))})));
  return new Table({width:{size:widths.reduce((a,b)=>a+b,0),type:WidthType.DXA},columnWidths:widths,rows:tr});
}
const legend=(t)=>new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:80,after:200,line:240},children:[new TextRun({text:t,italics:true,size:20,font:'Arial'})]});
const alinea=(t)=>new Paragraph({alignment:AlignmentType.JUSTIFIED,spacing:{line:360,before:0,after:120},indent:{left:709,hanging:425},children:runs(t)});
const C=[];
const ID='Processo nº 0155517-72.2026.8.05.0001';
const fig=(file,w,h,cap)=>[new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:80,after:60},children:[new ImageRun({type:'png',data:fs.readFileSync(file),transformation:{width:w,height:h}})]}),legend(cap)];
C.push(new Paragraph({alignment:AlignmentType.JUSTIFIED,spacing:{after:160,line:276},children:[new TextRun({text:'AO JUÍZO DA 7ª VARA DO SISTEMA DOS JUIZADOS ESPECIAIS DO CONSUMIDOR (MATUTINO) DA COMARCA DE SALVADOR — BAHIA',bold:true,size:24,font:'Arial'})]}));
C.push(new Paragraph({border:{bottom:{style:BorderStyle.SINGLE,size:3,color:'CCCCCC',space:1}},spacing:{after:160},children:[]}));
['**'+ID+'**','**Recorrente:** ROMUALDO RAMON ALMEIDA DE OLIVEIRA','**Recorrido:** BANCO SANTANDER (BRASIL) S.A.'].forEach(t=>C.push(plain(t,{after:60,align:AlignmentType.LEFT})));
C.push(Esp(200));
C.push(new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:80},children:[new TextRun({text:'RECURSO INOMINADO',bold:true,color:NAVY,size:30,font:'Arial'})]}));
C.push(new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:240},children:[new TextRun({text:'arts. 41 e 42 da Lei 9.099/95 — com pedido de gratuidade da justiça',italics:true,size:22,font:'Arial'})]}));
C.push(new Paragraph({border:{bottom:{style:BorderStyle.SINGLE,size:6,color:NAVY,space:1}},spacing:{after:200},children:[]}));

C.push(H1('Parte A — Petição de interposição'));
C.push(body('**ROMUALDO RAMON ALMEIDA DE OLIVEIRA**, já qualificado nos autos da ação declaratória de inexistência de relação obrigacional c/c repetição em dobro do indébito e indenização por danos morais que move em face de **BANCO SANTANDER (BRASIL) S.A.**, vem, **tempestivamente**, com fundamento no **art. 41 da Lei nº 9.099/95**, interpor **RECURSO INOMINADO** contra a r. sentença de Id. 206917636 (Págs. 446–447), que julgou improcedentes os pedidos, pelas razões anexas, que requer sejam recebidas e processadas.'));
C.push(body('**Tempestividade.** O Recorrente foi intimado da sentença em **___/___/2026** [VERIFICAR ANTES DE PROTOCOLAR a data exata; os autos mostram a conclusão da sentença em 02/10/2026]; o prazo é de 10 (dez) dias úteis (art. 42 da Lei 9.099/95 c/c art. 219 do CPC e Enunciado 165 do FONAJE).'));
C.push(body('**Preparo e gratuidade.** A gratuidade foi requerida na inicial (Id. 201679186, Págs. 2–3). A sentença determinou que, "em havendo requerimento de gratuidade", o pedido seja apreciado, com a apresentação de "documentos que comprovem a insuficiência de recursos [...], os quais devem acompanhar a petição de recurso" (Id. 206917636, Pág. 447). O pedido é **renovado** e instruído com o **Histórico de Empréstimo Consignado emitido pelo INSS (Doc. 1)**, conforme o tópico II.2 das razões. Requer-se a dispensa do preparo (art. 42, § 1º, da Lei 9.099/95 c/c arts. 98 e 99, § 7º, do CPC [VERIFICAR ANTES DE PROTOCOLAR]) e, apenas por cautela e sem prejuízo do pedido, que, em caso de indeferimento, seja fixado prazo para recolhimento, evitando-se a deserção.'));
C.push(body('Requer, ao final, o recebimento do recurso, a intimação do Recorrido para contrarrazões e a remessa à Egrégia Turma Recursal.'));
C.push(plain('Nestes termos, pede deferimento.',{align:AlignmentType.LEFT,indent:{firstLine:708},after:60}));
C.push(plain('Salvador/BA, ___ de outubro de 2026.',{align:AlignmentType.LEFT,indent:{firstLine:708},after:200}));
C.push(plain('CLEYTON DA SILVA BARBOSA',{align:AlignmentType.CENTER,after:0,bold:true}));
C.push(plain('OAB/MS 17.311 — OAB/BA 92.148',{align:AlignmentType.CENTER,after:300}));

C.push(new Paragraph({pageBreakBefore:true,alignment:AlignmentType.JUSTIFIED,spacing:{after:160,line:276},children:[new TextRun({text:'EGRÉGIA TURMA RECURSAL DOS JUIZADOS ESPECIAIS CÍVEIS E CRIMINAIS DO ESTADO DA BAHIA',bold:true,size:24,font:'Arial'})]}));
['**Recurso Inominado — '+ID+'** (origem: 7ª VSJE do Consumidor — Matutino — Salvador/BA)','**Recorrente:** ROMUALDO RAMON ALMEIDA DE OLIVEIRA','**Recorrido:** BANCO SANTANDER (BRASIL) S.A.'].forEach(t=>C.push(plain(t,{after:60,align:AlignmentType.LEFT})));
C.push(H1('Parte B — Razões do recurso inominado'));
C.push(plain('**Colenda Turma, Eméritos Julgadores,**',{align:AlignmentType.LEFT,after:160}));

C.push(H2('I — Síntese da demanda e da sentença recorrida'));
C.push(body('O Recorrente, aposentado por invalidez (NB 114.541.888-8), constatou no Meu INSS descontos, sob a rubrica de empréstimo consignado, relativos a dois contratos do Banco Santander que afirma jamais ter celebrado: o nº **555681960** (averbado em 21/04/2022) e o nº **573350776** (averbado em 01/08/2022, excluído em 22/11/2024), ambos com parcela de R$ 118,46 (Id. 201679186, Págs. 4–5). Pediu a declaração de inexistência, a repetição em dobro e indenização por danos morais.'));
C.push(body('O Recorrido contestou afirmando que as contratações "ocorreram por meio digital, com autenticação de senha, **por esse motivo não gera contrato físico assinado**" (Id. 205808669, Pág. 68), e que a ausência de "assinatura física do contratante" não impacta a higidez da contratação pela modalidade "clique único" (Pág. 70). Na audiência de 24/09/2026, o preposto foi questionado sobre a selfie/biometria e **constou em ata que, na contratação, não houve biometria** (Id. 206306294, Pág. 444; Id. 206306295, Pág. 445).'));
C.push(body('A sentença julgou improcedentes todos os pedidos. Afirmou que a inversão do ônus da prova não é automática; que o Recorrente "nega genericamente" a existência de contrato; e que "a acionada demonstrou a regularidade da contratação de empréstimo(s), conforme documentação eletrônica juntada aos autos, notadamente os contratos e os extratos em nome do autor", razão pela qual o Recorrente "não fez [...] prova do seu direito constitutivo, nos termos do artigo 373, I, do Código de Processo Civil" (Id. 206917636, Pág. 446).'));
C.push(body('**A *ratio decidendi* atacada:** o Juízo (i) pôs sobre o consumidor o ônus de provar que **não** contratou; (ii) considerou "contratos" documentos que **não são contratos**, pois não têm assinatura, aceite nem registro idôneo de autoria, e a própria ré admite que não há contrato assinado; (iii) tratou o depósito do valor em conta como prova de consentimento; e (iv) **não enfrentou** o que a ata registra sobre a ausência de biometria.'));

C.push(H2('II — Admissibilidade'));
C.push(H2('II.1 — Cabimento, tempestividade e interesse'));
C.push(body('O recurso é cabível (art. 41 da Lei 9.099/95), foi interposto no prazo de 10 dias úteis (art. 42) e o Recorrente tem interesse, pois teve todos os pedidos julgados improcedentes.'));
C.push(H2('II.2 — Gratuidade da justiça: comprovação pelo Histórico de Empréstimo Consignado do INSS'));
C.push(body('O Recorrente declarou, sob as penas da lei, não poder arcar com as despesas do processo sem prejuízo do próprio sustento (Id. 201679187). A declaração de pessoa natural presume-se verdadeira (art. 99, § 3º, do CPC), e o benefício só pode ser negado se houver nos autos elementos que evidenciem a falta dos pressupostos, após intimação da parte para comprová-los (art. 99, § 2º). A sentença exige documento comprobatório; o **Histórico de Empréstimo Consignado emitido pelo INSS (Doc. 1)**, documento oficial da própria autarquia, demonstra o comprometimento da renda do Recorrente:'));
C.push(table([5000,2000,2026],['Dado (benefício NB 114.541.888-8 — Aposentadoria por invalidez, acidente do trabalho)','Valor','Observação'],[
['Base de cálculo da margem (valor do benefício)','R$ 4.384,82','—'],
['Máximo de comprometimento permitido','R$ 1.753,93','—'],
['Descontos em empréstimos consignados','R$ 1.522,94','12 empréstimos ativos'],
['Cartão consignado (RMC)','R$ 219,24','—'],
['Cartão benefício (RCC)','R$ 219,24','—'],
['**Total comprometido**','**R$ 1.961,42**','**44,7% do benefício**'],
['**Margem extrapolada**','**R$ 207,49**','Acima do limite legal'],
['**Renda líquida aproximada após as consignações**','**R$ 2.423,40**','55,3% do benefício'],
],{right:[1]}));
C.push(legend('Quadro 1 — Margem consignável e comprometimento da renda (Doc. 1)'));
C.push(body('O Histórico demonstra que o Recorrente tem **44,7%** do benefício comprometido com 12 empréstimos ativos e cartões consignados, em valor **R$ 207,49 acima da margem permitida**. A renda líquida restante, em torno de R$ 2.423,40, é a única de que dispõe e sustenta sua subsistência e a de sua família. Nessas circunstâncias, o pagamento de preparo recursal e o risco da sucumbência recursal comprometem o mínimo existencial (art. 5º, LXXIV, da CF/88; art. 98 do CPC). Requer-se a **concessão da gratuidade**, com dispensa do preparo (art. 99, § 7º, do CPC [VERIFICAR ANTES DE PROTOCOLAR]); se o Colegiado entender necessária prova complementar (contracheque/extrato de pagamento do benefício, declaração de imposto de renda), requer-se **intimação prévia para complementação** (art. 99, § 2º) e, em último caso, prazo para recolhimento, sem deserção. A gratuidade suspende, ainda, a exigibilidade de eventual sucumbência recursal (art. 98, § 3º, do CPC [VERIFICAR ANTES DE PROTOCOLAR]).'));

C.push(H2('III — Delimitação do objeto e mapa dos fundamentos da sentença'));
C.push(body('Como a sentença é de **improcedência total**, devolve-se à Turma o capítulo integral: a inexistência dos contratos, a repetição em dobro e a indenização por danos morais.'));
C.push(table([480,3500,2400,2646],['#','Fundamento da sentença (Id. 206917636, Pág. 446)','Erro apontado','Atacado em'],[
['1','Inversão do ônus "não automática"; o Recorrente "nega genericamente" o contrato e "não fez prova do seu direito constitutivo"','Erro de direito: exigiu prova de fato negativo; ônus da contratação é do fornecedor','IV.1'],
['2','"A acionada demonstrou a regularidade da contratação [...] notadamente os contratos"','Erro de fato: não há contrato assinado, aceite ou registro de autoria; a ré o admite','IV.2'],
['3','Idem: "e os extratos em nome do autor"','Erro de direito: depósito em conta não prova consentimento; art. 39, III, e parágrafo único do CDC','IV.3'],
['4','Silêncio sobre a ausência de biometria registrada em ata e sobre as inconsistências dos logs apontadas na réplica','Omissão (art. 489, § 1º, IV, do CPC)','IV.4 e IV.5'],
['5','Sem dano: "não demonstrada a dor, a ofensa ou o constrangimento" (Pág. 447)','Erro de direito: dano presumido em descontos sobre benefício alimentar','IV.6 e IV.7'],
]));
C.push(legend('Quadro 2 — Fundamentos da sentença, erros e seções de ataque'));

C.push(H2('IV — Razões de reforma'));
C.push(H2('IV.1 — O erro na distribuição do ônus da prova'));
C.push(body('A sentença afirma que o Recorrente "nega genericamente" a existência de contrato e que "não fez [...] prova do seu direito constitutivo" (art. 373, I, do CPC). Exigir do consumidor a prova de que **não** contratou é exigir prova diabólica de fato negativo. **O fato que daria validade ao desconto, a manifestação de vontade do beneficiário, é fato impeditivo do direito do autor, e prová-lo incumbe ao réu (art. 373, II, do CPC)**, que é quem produz e conserva os documentos, os registros de autenticação e os logs da contratação. A responsabilidade é objetiva (art. 14 do CDC; Súmula 479/STJ), a hipossuficiência técnica é manifesta e a verossimilhança está demonstrada **pelas próprias admissões do Recorrido**: não há contrato assinado, e não houve biometria. A distribuição dinâmica do art. 373, § 1º, do CPC leva ao mesmo resultado, e o art. 6º, VIII, do CDC permite a inversão, pedida na inicial. A sentença, ao tratar a negativa como "genérica" e exigir "prova mínima" do consumidor, inverteu o ônus.'));
C.push(body('A autorização para o desconto em benefício previdenciário, ademais, é ato do **beneficiário** (art. 6º da Lei 10.820/2003 [VERIFICAR ANTES DE PROTOCOLAR]); a comprovação dessa autorização é requisito do próprio negócio e cabe à instituição que o averbou.'));
C.push(cons('o ônus de provar a contratação válida era do Recorrido, e a improcedência por "ausência de prova do direito constitutivo" pelo consumidor contraria o art. 373, II, do CPC e a Súmula 479/STJ.'));

C.push(H2('IV.2 — Não há contrato: os "contratos" juntados não têm assinatura, aceite nem registro de autoria'));
C.push(body('A sentença considerou provada a contratação por "os contratos". **Os documentos de Ids. 205808670 e 205808671 não são contratos assinados.** São "COMPROVANTE DE CONTRATAÇÃO DE CRÉDITO CONSIGNADO" **emitidos pelo próprio banco** (datas de emissão 22/04/2022 e 01/08/2022), com os dados da operação e um texto-padrão em que o "cliente" supostamente "reconhece a validade e legitimidade desta operação, realizada mediante a digitação da sua senha eletrônica" (Id. 205808670, Págs. 76–77). Não contêm assinatura, física ou eletrônica, do Recorrente, nem registro de aceite com data, hora, dispositivo e versão do termo aceito. A declaração impressa no formulário de que o cliente "reconhece" a operação é declaração **da própria ré**, e não prova de que o cliente a fez. As demais páginas são impressões de "Dados do Contrato" do sistema interno (Id. 205808670, Pág. 82; Id. 205808671, Pág. 91), com a indicação "Canal Operação: Mobile".'));
C.push(body('**A própria Recorrida confessa que não há contrato assinado.** Na contestação, afirma: "As contratações ocorreram por meio digital, com autenticação de senha, **por esse motivo não gera contrato físico assinado**, dada a autenticação por senha de uso pessoal e intransferível" (Id. 205808669, Pág. 68); e que a "ausência de termo por escrito com a assinatura física do contratante, substituído, nesse sistema, pela automatização das contratações mediante senha eletrônica ou impressão digital, não impacta a higidez da contratação" (Pág. 70). Reconhece, assim, que **inexiste instrumento assinado** e que sua prova da contratação se resume a que alguém digitou uma senha em um aplicativo, sem demonstrar quem.'));
C.push(body('A invocação da Lei 14.063/2020 (art. 4º) não supre a falta. A assinatura eletrônica simples ou avançada exige que o meio "permita identificar o seu signatário" e esteja "associada ao signatário de maneira unívoca", com dados sob seu "controle exclusivo". **Uma senha de acesso ao aplicativo não é assinatura de documento determinado**: serve para entrar no sistema, não para atribuir ao titular a declaração de vontade constante de uma proposta específica. A Recorrida não juntou a proposta, o termo, o registro de aceite, o *token* de confirmação da operação nem o log que associe a senha **a esse documento**. Quanto à adoção de meio diverso de assinatura, a MP 2.200-2/2001 (art. 10, § 2º) condiciona sua validade a que tenha sido "admitido pelas partes como válido ou aceito pela pessoa a quem for oposto o documento": o Recorrente **não admitiu nem aceitou** esse meio; ao contrário, nega a contratação. Quem se vale de contratação sem instrumento deve provar a manifestação de vontade, e a ausência de oportunidade de conhecer o conteúdo do contrato retira dele a força obrigatória (art. 46 do CDC [VERIFICAR ANTES DE PROTOCOLAR]).'));
C.push(body('**O contrato nº 573350776 é refinanciamento do nº 555681960**: destinou R$ 4.990,76 à liquidação do primeiro e entregou apenas R$ 418,29 em dinheiro novo (Id. 205808669, Pág. 68; Id. 205808671, Pág. 83). Inexistente o contrato originário, o refinanciamento que dele deriva não pode ser tratado como operação autônoma e regular, sob pena de se convalidar por via oblíqua a contratação impugnada (réplica, Id. 205878802, seção VI).'));
C.push(cons('não há contrato assinado, aceite ou registro de autoria, e a Recorrida o admite; a "regularidade da contratação" afirmada na sentença não tem suporte em prova.'));

C.push(H2('IV.3 — Os extratos: o depósito do valor em conta não prova consentimento'));
C.push(body('A sentença tem como prova da contratação "os extratos em nome do autor". Mas **o depósito do valor em conta é ato do próprio banco**: é a instituição que credita o valor e que, portanto, pode fazê-lo **sem pedido do cliente**. O crédito na conta não prova que o cliente solicitou o empréstimo, tampouco o que ele sabia a respeito. O CDC o prevê expressamente: fornecer serviço "sem solicitação prévia" é prática abusiva (art. 39, III), e os serviços e produtos entregues nessa hipótese "equiparam-se às amostras grátis, inexistindo obrigação de pagamento" (art. 39, parágrafo único [VERIFICAR ANTES DE PROTOCOLAR]). Assim, **sem prova da solicitação prévia e do consentimento expresso, o mero crédito em conta não obriga o consumidor**.'));
C.push(body('O que os extratos mostram, ainda, é **incompatível com o "proveito consciente" que a Recorrida alega**. No contrato nº 555681960, o crédito de R$ 4.768,65 foi seguido, **no mesmo dia (22/04/2022)**, de "APLICAÇÃO CDB/RDB" de **R$ 4.700,00 (98,5% do valor)**, em produto do próprio Recorrido, e de transferências por PIX a terceiros, com saldo final do dia zerado (Id. 205808669, Pág. 65). No contrato nº 573350776, o crédito de R$ 418,29 foi seguido, no mesmo dia (01/08/2022), de PIX a terceiros e saldo final igual a zero (Pág. 68). A Recorrida **não juntou log algum que identifique quem comandou a aplicação em CDB/RDB ou os PIX**, nem o terminal, o IP e a autenticação de cada uma dessas operações. O ônus de demonstrar que foi o Recorrente quem as ordenou, e que as ordenou com ciência da origem do dinheiro, era seu.'));
C.push(cons('o depósito em conta e as movimentações no mesmo dia não provam o consentimento e, sem prova da solicitação prévia, não geram obrigação (art. 39, III e parágrafo único, do CDC).'));

C.push(H2('IV.4 — A confissão do preposto: na contratação, não houve biometria'));
C.push(body('Na audiência una de 24/09/2026, o advogado do Recorrente questionou o preposto do Recorrido sobre a selfie/biometria e formulou requerimento "para constar em Ata acerca do depoimento do preposto [...] **que na contratação não houve biometria**" (Id. 206306294, Pág. 444; Id. 206306295, Pág. 445). Consta que o preposto foi **"também questionado sobre a selfie/biometria"** e que ficou registrado que **a contratação não teve biometria**. O Recorrido, presente por seu preposto e por seu advogado, **não impugnou o registro**: a ata consigna apenas que reiterou a contestação e requereu a procedência (Pág. 444). A gravação integral da audiência consta dos links da ata [VERIFICAR ANTES DE PROTOCOLAR e indicar o minuto da resposta do preposto].'));
C.push(body('**Trata-se de declaração da parte, prestada por quem a representa, sobre fato desfavorável a seus interesses e favorável ao adversário** (confissão: arts. 389 a 391 do CPC [VERIFICAR ANTES DE PROTOCOLAR]). E é coerente com o resto dos autos: **a contestação não alega biometria**; alega apenas "senha/touch" e o aplicativo "ID Santander" (Id. 205808669, Pág. 62). A única imagem do Recorrente que consta dos autos é a **selfie com o RG tirada na abertura da conta, em setembro de 2019** (Id. 205808677, Pág. 280; proposta assinada digitalmente em 23/09/2019, Pág. 275), isto é, **quase três anos antes** das contratações de 2022. **Nenhuma selfie, fotografia ou biometria foi capturada nas operações impugnadas.**'));
C.push(body('**A sentença não enfrentou essa confissão nem a ata.** Limitou-se a dizer que a regularidade estava demonstrada por "documentação eletrônica". Argumento relevante, suscitado na audiência e registrado em ata, que a sentença deveria ter apreciado (art. 489, § 1º, IV, do CPC [VERIFICAR ANTES DE PROTOCOLAR]), é devolvido a esta Turma com profundidade de fato e direito (art. 1.013, §§ 1º e 2º, do CPC). Sem biometria, sem contrato assinado e sem registro técnico confiável (tópico seguinte), **a Recorrida só tem a seu favor a alegação de que alguém digitou uma senha**, o que é insuficiente para atribuir ao Recorrente a contratação de crédito que lhe retira renda de natureza alimentar por 84 meses.'));
C.push(cons('a ata registra a confissão de que não houve biometria na contratação; a sentença a ignorou e reputou provada a autoria sem o elemento de autenticação mais seguro.'));

C.push(H2('IV.5 — As telas e os logs: documentos internos, incompletos e inconsistentes'));
C.push(body('Além dos "comprovantes" e das telas de "Dados do Contrato", a Recorrida colou em sua contestação **planilhas e prints de sistema interno** (Id. 205808669, Págs. 63–67) para tentar demonstrar autoria. Eles não têm fé pública nem chancela de terceiro e **foram reproduzidos na peça de defesa, sem arquivo original ou metadados**. O art. 425, V, do CPC confere valor às reproduções digitais atestadas pelo emitente como referentes ao caso concreto; recortes de planilha colados em petição não são atestado. E, examinados, **não comprovam, antes fragilizam, a autoria**, como apontado na réplica (Id. 205878802, seção IV):'));
C.push(...fig('fig1_log.png',480,226,'Figura 1 — Planilha de "log" colada na contestação para o contrato nº 555681960 (Id. 205808669, Pág. 63): campos "conta_destino" = "...unknown", "cpf_cnpj_originac" e "cpf_cnpj_recebec", "id_telefone" e "geo_latitude"/"geo_longitud"'));
C.push(alinea('a)\t**"conta_destino" desconhecida.** O campo de conta de destino da operação registra "0000000000000unknown": o sistema da própria Recorrida não identifica o destino da transação.'));
C.push(alinea('b)\t**Documentos de origem e destino estranhos.** Os campos "cpf_cnpj_originac" e "cpf_cnpj_recebec" trazem números (766088420 e 2076442051) que não correspondem ao CPF do Recorrente (506.580.505-91) nem ao CNPJ da Recorrida (90.400.888/0001-42), sem qualquer esclarecimento [VERIFICAR ANTES DE PROTOCOLAR a leitura dos números na planilha, de baixa resolução].'));
C.push(alinea('c)\t**"IMEI" que não é IMEI.** A contestação afirma que a operação foi feita em aparelho Android "de IMEI 9XDh13FjPOfcS1wiSmyhkh4Zw89y2A9PyYolkiaRLLc" (Id. 205808669, Págs. 62 e 65). Um IMEI é, por definição, um número de **15 dígitos**; a cadeia apresentada é alfanumérica, e é o valor que a planilha registra no campo "id_telefone" (identificador de sessão/aplicativo, e não de hardware). Além disso, **o mesmo identificador aparece nas duas contratações, com mais de três meses de diferença**, sem que a Recorrida demonstre a quem pertence o aparelho, quando e como foi cadastrado.'));
C.push(alinea('d)\t**Geolocalização inválida e aproximada.** Os campos numéricos "geo_latitude" ("-383.956.087") e "geo_longitud" ("-129.592.851") trazem valores fora do intervalo possível de coordenadas (latitude de -90 a +90; longitude de -180 a +180). A "localização" que a Recorrida apresenta é um **geohash de 6 caracteres** (Págs. 64 e 67), que **delimita uma área de mais de um quilômetro**, convertido em site público de conversão ("Geohash Converter") e lançado no Google Maps **pelos advogados da Recorrida**, e não um registro técnico de GPS com carimbo de data e hora.'));
C.push(...fig('fig2_mapa.png',440,254,'Figura 2 — Mapa lançado pela Recorrida (Id. 205808669, Pág. 64): do endereço do Recorrente (R. 5 de Novembro, 22 — Pau Miúdo) ao ponto da "geolocalização" do contrato nº 555681960 ("Barraca do Valder, Av. Octávio Mangabeira"): 22 min / 15,1 km'));
C.push(body('O resultado é contraproducente para a Recorrida: **o ponto de "geolocalização" que ela própria lançou para o contrato nº 555681960 fica a cerca de 15 km do endereço do Recorrente** (Pág. 64), o que, se algo, aponta que a operação não foi feita onde ele reside [VERIFICAR ANTES DE PROTOCOLAR a leitura do mapa, de baixa resolução]; para o contrato nº 573350776, o ponto fica próximo (Pág. 67), mas um geohash de 6 caracteres não permite sequer afirmar a que imóvel corresponde. Cabe à Recorrida, e não ao consumidor, a prova técnica da sessão (IP associado a assinante, dispositivo cadastrado, geolocalização precisa, confirmação por *token*), que **não foi produzida**; a lacuna, sob inversão do ônus, opera contra quem a detém. No Juizado não se admite perícia complexa (art. 35, IV, da Lei 9.099/95); por isso a lacuna é argumento de mérito.'));
C.push(cons('as telas e planilhas da Recorrida são unilaterais, incompletas e inconsistentes, e não suprem a ausência de contrato assinado e de biometria.'));

C.push(H2('IV.6 — Da repetição em dobro'));
C.push(body('Declarada a inexistência dos contratos, os descontos sobre o benefício são indevidos e devem ser restituídos **em dobro**, nos termos do art. 42, parágrafo único, do CDC. A Corte Especial do STJ fixou que a restituição em dobro "independe da natureza do elemento volitivo do fornecedor", bastando que a cobrança indevida seja contrária à boa-fé objetiva (EAREsp 676.608/RS, Rel. Min. Og Fernandes, j. 21/10/2020, invocado na inicial [VERIFICAR ANTES DE PROTOCOLAR]). Cobrar desconto em benefício previdenciário com base em contrato do qual não há assinatura, aceite nem biometria é conduta objetivamente contrária à boa-fé. Segundo a inicial, os descontos somam **R$ 3.672,26** (R$ 3.198,42 do contrato nº 573350776 e R$ 473,84 do nº 555681960 — Id. 201679186, Págs. 4–5), de modo que a repetição em dobro corresponde a **R$ 7.344,52**, valores a conferir no extrato do INSS [VERIFICAR ANTES DE PROTOCOLAR], com correção desde cada desconto (Súmula 43/STJ) e juros de mora desde o evento danoso (Súmula 54/STJ). Em atenção ao art. 38, parágrafo único, da Lei 9.099/95, o pedido é certo e determinado.'));
C.push(body('**Subsidiariamente**, caso a Turma entenda que o valor creditado ao Recorrente em conta (R$ 4.768,65 e R$ 418,29, totalizando R$ 5.186,94) deva ser restituído em razão da nulidade, requer-se a **compensação** com o indébito, sem prejuízo da restituição em dobro do excedente.'));

C.push(H2('IV.7 — Do dano moral, presumido nos descontos indevidos sobre benefício alimentar'));
C.push(body('A sentença negou o dano moral por não haver "demonstração da dor, da ofensa ou do constrangimento" (Pág. 447). O dano, aqui, é **presumido**: o desconto mensal, **por cerca de dois anos e meio**, sobre benefício previdenciário de natureza alimentar, por contrato que o consumidor não celebrou, atinge diretamente o mínimo existencial e os direitos da personalidade (art. 5º, X, da CF/88; art. 14 do CDC; Súmula 479/STJ), e independe de prova de abalo psíquico específico. O benefício do Recorrente já está comprometido em 44,7% com outros empréstimos (Quadro 1), o que agrava a lesão causada por descontos indevidos.'));
C.push(body('**Parâmetros.** (a) REsp 2.201.694/SP (Doc. 2): 3ª Turma do STJ, por maioria (Rel. p/ acórdão Min. Nancy Andrighi; j. 05/08/2025), reconheceu dano moral presumido pelo tratamento indevido de dados "diante da forte sensação de insegurança" do titular, e fixou R$ 11.000,00; (b) sentença do processo nº 0022386-55.2026.8.05.0080 (5ª VSJ de Feira de Santana/BA) (Doc. 3): R$ 5.000,00 por relação bancária constituída sem prova de contratação, sem negativação. São casos de lesão diversa (dados pessoais; conta bancária), invocados apenas como **parâmetros de ordem de grandeza**; a lesão aqui, por envolver desconto reiterado sobre renda alimentar, é ao menos igualmente grave.'));
C.push(body('Mantém-se o valor da inicial, **R$ 40.000,00** (Id. 201679186, Págs. 11–12). Caso a Turma não o acolha, requer-se o **arbitramento pelo próprio Colegiado**, em valor **não inferior a R$ 5.000,00**, com juros de mora desde o evento danoso (Súmula 54/STJ) e correção monetária desde o arbitramento (Súmula 362/STJ), observado, para os períodos a partir de 30/08/2024, o art. 406 do CC, na redação da Lei 14.905/2024.'));
C.push(cons('constatada a ausência de contratação, os descontos são indevidos e o dano é presumido; impõem-se a repetição em dobro e a indenização.'));

C.push(H2('V — Prequestionamento'));
C.push(body('Para fins de eventual Recurso Extraordinário (art. 102, III, da CF/88) e de pedido de uniformização de jurisprudência, ficam prequestionados os arts. 5º, X, XXXV e LXXIV, da CF/88; os arts. 6º, VIII, 14, 39, III e parágrafo único, 42, parágrafo único, e 46 do CDC; a Súmula 479/STJ; o art. 6º da Lei 10.820/2003; os arts. 4º da Lei 14.063/2020 e 10, § 2º, da MP 2.200-2/2001; os arts. 104 do CC; os arts. 373, 389 a 391, 425, V, e 489, § 1º, IV, do CPC; e os arts. 98 e 99 do CPC.'));

C.push(H2('VI — Pedidos'));
C.push(body('Ante o exposto, requer o Recorrente:'));
[
'a)\tO **recebimento do recurso** com a **concessão da gratuidade da justiça**, dispensado o preparo (art. 42, § 1º, da Lei 9.099/95; arts. 98 e 99 do CPC), à vista do Histórico de Empréstimo Consignado do INSS (Doc. 1); subsidiariamente, a intimação para complementação da prova (art. 99, § 2º, do CPC) e, em último caso, prazo para recolhimento, sem deserção;',
'b)\tO **conhecimento e provimento do recurso** para reformar a sentença de Id. 206917636 e **declarar a inexistência da relação obrigacional** decorrente dos contratos de empréstimo consignado nº 555681960 e nº 573350776, por ausência de contrato assinado, de aceite, de biometria e de prova de manifestação de vontade, com a consequente inexigibilidade dos débitos;',
'c)\tA **manutenção da inversão do ônus da prova** (art. 6º, VIII, do CDC; art. 373, § 1º, do CPC) e o reconhecimento do valor probatório da **ata de audiência** (Id. 206306294), quanto à ausência de biometria na contratação;',
'd)\tA condenação do Recorrido à **restituição em dobro** de todos os valores descontados do benefício (R$ 3.672,26 em simples, R$ 7.344,52 em dobro, conforme a inicial), com correção monetária desde cada desconto e juros de mora desde o evento danoso; subsidiariamente, a compensação com o valor creditado em conta, sem prejuízo da restituição em dobro do excedente;',
'e)\tA condenação do Recorrido ao pagamento de **indenização por danos morais de R$ 40.000,00**, valor da inicial, ou, subsidiariamente, o **arbitramento judicial** pela Turma, em valor **não inferior a R$ 5.000,00**, tomando-se por parâmetro o REsp 2.201.694/SP (R$ 11.000,00) e a sentença do processo nº 0022386-55.2026.8.05.0080 (R$ 5.000,00);',
'f)\tA ausência de condenação do Recorrente em custas e honorários, por ser beneficiário da gratuidade, e a condenação do Recorrido na sucumbência recursal, se vencido (art. 55 da Lei 9.099/95);',
'g)\tQue as intimações sejam feitas em nome do advogado **CLEYTON DA SILVA BARBOSA, OAB/MS 17.311 e OAB/BA 92.148**.'
].forEach(t=>C.push(alinea(t)));
C.push(plain('**Documentos anexos:** Doc. 1 — Histórico de Empréstimo Consignado emitido pelo INSS (NB 114.541.888-8); Doc. 2 — Acórdão do REsp 2.201.694/SP (STJ); Doc. 3 — Sentença do processo nº 0022386-55.2026.8.05.0080 (5ª VSJ de Feira de Santana/BA).',{align:AlignmentType.JUSTIFIED,after:200}));
C.push(plain('Nestes termos, pede deferimento.',{align:AlignmentType.LEFT,indent:{firstLine:708},after:60}));
C.push(plain('Salvador/BA, ___ de outubro de 2026.',{align:AlignmentType.LEFT,indent:{firstLine:708},after:400}));
C.push(plain('CLEYTON DA SILVA BARBOSA',{align:AlignmentType.CENTER,after:0,bold:true}));
C.push(plain('OAB/MS 17.311 — OAB/BA 92.148',{align:AlignmentType.CENTER,after:0}));
const doc=new Document({styles:{default:{document:{run:{font:'Arial',size:24}}}},
 sections:[{properties:{page:{size:{width:11906,height:16838},margin:{top:1701,bottom:1134,left:1701,right:1134}}},
 footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:ID+' — Recurso Inominado — página ',size:18,font:'Arial'}),new TextRun({children:[PageNumber.CURRENT],size:18,font:'Arial'}),new TextRun({text:' de ',size:18,font:'Arial'}),new TextRun({children:[PageNumber.TOTAL_PAGES],size:18,font:'Arial'})]})]})},
 children:C}]});
Packer.toBuffer(doc).then(b=>{fs.writeFileSync('recurso_inominado_consignado.docx',b);console.log('ok',b.length)});
