const fs=require('fs');
const D=require('/opt/node-tools/node_modules/docx');
const {Document,Packer,Paragraph,TextRun,Table,TableRow,TableCell,AlignmentType,BorderStyle,WidthType,ShadingType,LevelFormat,VerticalAlign,Footer,PageNumber}=D;
const NAVY='1F3864',BLUE='2E75B6';
function runs(t,o={}){ // **bold**
  return t.split('**').map((s,i)=>new TextRun({text:s,bold:(i%2===1)||o.bold,italics:o.italics,size:o.size||24,color:o.color,font:'Arial'})).filter(r=>true);
}
const body=(t)=>new Paragraph({alignment:AlignmentType.JUSTIFIED,spacing:{line:360,lineRule:'auto',before:0,after:160},indent:{firstLine:709},children:runs(t)});
const plain=(t,o={})=>new Paragraph({alignment:o.align||AlignmentType.JUSTIFIED,spacing:{line:360,before:0,after:o.after??160},indent:o.indent||{},children:runs(t,o)});
const H1=(t)=>new Paragraph({keepNext:true,spacing:{before:320,after:140,line:276},indent:{},border:{bottom:{style:BorderStyle.SINGLE,size:6,color:BLUE,space:1}},children:[new TextRun({text:t.toUpperCase(),bold:true,color:NAVY,size:24,font:'Arial'})]});
const H2=(t)=>new Paragraph({keepNext:true,spacing:{before:280,after:120,line:276},indent:{},children:[new TextRun({text:t.toUpperCase(),bold:true,color:NAVY,size:24,font:'Arial'})]});
const cons=(t)=>new Paragraph({alignment:AlignmentType.JUSTIFIED,spacing:{line:360,before:0,after:160},indent:{firstLine:709},children:[new TextRun({text:'Consequência processual: ',size:24,font:'Arial'}),...runs(t)]});
const Esp=(h)=>new Paragraph({spacing:{before:0,after:h},children:[]});
const bd={style:BorderStyle.SINGLE,size:1,color:'BECFE0'};const B={top:bd,bottom:bd,left:bd,right:bd};
function table(widths,head,rows,opt={}){
  const mk=(txt,w,fill,bold,al)=>new TableCell({width:{size:w,type:WidthType.DXA},borders:B,verticalAlign:VerticalAlign.CENTER,shading:{type:ShadingType.CLEAR,color:'auto',fill},margins:{top:70,bottom:70,left:110,right:110},children:[new Paragraph({alignment:al||AlignmentType.LEFT,spacing:{line:240,before:0,after:0},children:runs(String(txt),{size:20,bold,color:bold&&fill==='F0F4F8'?NAVY:undefined})})]});
  const tr=[new TableRow({tableHeader:true,cantSplit:true,children:head.map((h,i)=>mk(h,widths[i],'F0F4F8',true))})];
  rows.forEach((r,ri)=>tr.push(new TableRow({cantSplit:true,children:r.map((c,i)=>mk(c,widths[i],ri%2?'F7F9FB':'FFFFFF',false,(opt.right&&opt.right.includes(i))?AlignmentType.RIGHT:AlignmentType.LEFT))})));
  return new Table({width:{size:widths.reduce((a,b)=>a+b,0),type:WidthType.DXA},columnWidths:widths,rows:tr});
}
const legend=(t)=>new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:80,after:200,line:240},children:[new TextRun({text:t,italics:true,size:20,font:'Arial'})]});
const alinea=(t)=>new Paragraph({alignment:AlignmentType.JUSTIFIED,spacing:{line:360,before:0,after:120},indent:{left:709,hanging:425},children:runs(t)});
const C=[];
const ID='Processo nº 0003528-84.2026.8.05.0141';
// ===== PARTE A
C.push(new Paragraph({alignment:AlignmentType.JUSTIFIED,spacing:{after:160,line:276},children:[new TextRun({text:'AO JUÍZO DA 1ª VARA DO SISTEMA DOS JUIZADOS ESPECIAIS DA COMARCA DE JEQUIÉ — BAHIA',bold:true,size:24,font:'Arial'})]}));
C.push(new Paragraph({border:{bottom:{style:BorderStyle.SINGLE,size:3,color:'CCCCCC',space:1}},spacing:{after:160},children:[]}));
['**'+ID+'**','**Recorrente:** LUCAS SOUZA CHAVES','**Recorrida:** PICPAY BANK — BANCO MÚLTIPLO S.A.'].forEach(t=>C.push(plain(t,{after:60,align:AlignmentType.LEFT})));
C.push(Esp(200));
C.push(new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:80},children:[new TextRun({text:'RECURSO INOMINADO',bold:true,color:NAVY,size:30,font:'Arial'})]}));
C.push(new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:240},children:[new TextRun({text:'arts. 41 e 42 da Lei 9.099/95 — com pedido de gratuidade da justiça e de arbitramento de danos morais',italics:true,size:22,font:'Arial'})]}));
C.push(new Paragraph({border:{bottom:{style:BorderStyle.SINGLE,size:6,color:NAVY,space:1}},spacing:{after:200},children:[]}));
C.push(H1('Parte A — Petição de interposição'));
C.push(body('**LUCAS SOUZA CHAVES**, já qualificado nos autos da ação declaratória de inexistência de relação jurídica c/c obrigação de fazer e indenização por danos morais que move em face de **PICPAY BANK — BANCO MÚLTIPLO S.A.**, vem, **tempestivamente**, com fundamento no **art. 41 da Lei nº 9.099/95**, interpor **RECURSO INOMINADO** contra a r. sentença de Id. 206519760 (Págs. 239–241), na parte em que rejeitou os pedidos de indenização por danos morais e por desvio produtivo, pelas razões anexas, que requer sejam recebidas e processadas.'));
C.push(body('**Tempestividade.** A sentença foi intimada em **___/___/2026** [VERIFICAR ANTES DE PROTOCOLAR]; o prazo é de 10 (dez) dias (art. 42 da Lei 9.099/95), de modo que o recurso é tempestivo.'));
C.push(body('**Preparo e gratuidade.** A gratuidade da justiça foi requerida na inicial (Id. 202266797, Págs. 1–2; declaração de hipossuficiência, Id. 202266798) e **não foi apreciada** na sentença, que apenas dispensou custas e honorários no primeiro grau (art. 55 da Lei 9.099/95). O pedido é **renovado** nesta oportunidade e instruído com a **Carteira de Trabalho Digital do Recorrente (Doc. 1)**, conforme demonstrado no tópico II.2 das razões. Requer-se a dispensa do preparo (art. 42, § 1º, da Lei 9.099/95 c/c art. 98 e art. 99, § 7º, do CPC [VERIFICAR ANTES DE PROTOCOLAR]) e, apenas por cautela e sem prejuízo do pedido, que, em caso de indeferimento, seja fixado prazo para o recolhimento, evitando-se a deserção.'));
C.push(body('Requer, ao final, o recebimento do recurso, a intimação da Recorrida para contrarrazões e a remessa à Egrégia Turma Recursal.'));
C.push(plain('Nestes termos, pede deferimento.',{align:AlignmentType.LEFT,indent:{firstLine:708},after:60}));
C.push(plain('Jequié/BA, ___ de outubro de 2026.',{align:AlignmentType.LEFT,indent:{firstLine:708},after:200}));
C.push(plain('CLEYTON DA SILVA BARBOSA',{align:AlignmentType.CENTER,after:0,bold:true}));
C.push(plain('OAB/MS 17.311 — OAB/BA 92.148 [VERIFICAR inscrição suplementar]',{align:AlignmentType.CENTER,after:300}));

// ===== PARTE B
C.push(new Paragraph({pageBreakBefore:true,alignment:AlignmentType.JUSTIFIED,spacing:{after:160,line:276},children:[new TextRun({text:'EGRÉGIA TURMA RECURSAL DOS JUIZADOS ESPECIAIS CÍVEIS E CRIMINAIS DO ESTADO DA BAHIA',bold:true,size:24,font:'Arial'})]}));
['**Recurso Inominado — '+ID+'** (origem: 1ª Vara do Sistema dos Juizados de Jequié/BA)','**Recorrente:** LUCAS SOUZA CHAVES','**Recorrida:** PICPAY BANK — BANCO MÚLTIPLO S.A.'].forEach(t=>C.push(plain(t,{after:60,align:AlignmentType.LEFT})));
C.push(H1('Parte B — Razões do recurso inominado'));
C.push(plain('**Colenda Turma, Eméritos Julgadores,**',{align:AlignmentType.LEFT,after:160}));

C.push(H2('I — Síntese da demanda e da sentença recorrida'));
C.push(body('O Recorrente consultou o Registrato do Banco Central e descobriu relacionamento em seu nome e CPF com a Recorrida, **ativo desde 06/06/2020**, que jamais solicitou nem autorizou (Id. 202266801, Pág. 18). Ajuizou ação declaratória c/c obrigação de fazer e indenização por danos morais (R$ 8.000,00) e por desvio produtivo (R$ 2.000,00) (Id. 202266797, Pág. 8).'));
C.push(body('A sentença (Id. 206519760) julgou **parcialmente procedente** o pedido: (a) declarou a inexistência da relação jurídica, "reconhecendo a ausência de comprovação de contratação válida"; (b) determinou o encerramento da conta e a atualização do CCS/Registrato; (c) confirmou a tutela de urgência. Rejeitou, porém, as indenizações, por entender que "não se verifica prova de repercussão concreta sobre os direitos da personalidade", que a possibilidade de uso da conta seria "consequência hipotética", que o vínculo "remontava ao ano de 2020" sem repercussão demonstrada e que o desvio produtivo não foi provado, por constar o marcador "[DATA]" na narrativa de tentativas administrativas.'));
C.push(body('**A *ratio decidendi* atacada:** o Juízo reconheceu a fraude e a falha na prestação do serviço, mas **exigiu prova de consequência concreta (negativação, dívida, prejuízo patrimonial) para indenizar**, tratando como "hipotético" o dano que decorre, por si, da abertura e manutenção, por seis anos, de relação financeira em nome do consumidor sem o seu consentimento.'));

C.push(H2('II — Admissibilidade'));
C.push(H2('II.1 — Cabimento, tempestividade e interesse'));
C.push(body('O recurso é cabível (art. 41 da Lei 9.099/95), foi interposto no prazo de 10 dias (art. 42) e o Recorrente tem interesse, pois sucumbiu no capítulo indenizatório, que lhe foi integralmente negado.'));
C.push(H2('II.2 — Gratuidade da justiça: comprovação pela CTPS'));
C.push(body('O Recorrente declarou, sob as penas da lei, não poder arcar com as despesas do processo sem prejuízo do próprio sustento (Id. 202266798). Presume-se verdadeira a declaração de pessoa natural (art. 99, § 3º, do CPC), e o juiz só pode indeferir o benefício se houver nos autos elementos que evidenciem a falta dos pressupostos legais, após intimar a parte a comprová-los (art. 99, § 2º). Nada nos autos infirma a declaração. Ao contrário, a **Carteira de Trabalho Digital (Doc. 1)**, assinada digitalmente pela Dataprev em 29/07/2026, a confirma:'));
C.push(table([3400,5626],['Dado da CTPS Digital (Doc. 1)','Informação'],[
['Vínculo atual','MACIVALDO SOUZA COELHO — Jequié/BA; cargo de **Estoquista** (CBO 4141-05); contrato por prazo indeterminado; **admissão em 20/01/2021**; vínculo em aberto ("a (atual)")'],
['Remuneração atual','**R$ 1.653,00 por mês**, desde 01/04/2026 (R$ 1.621,00 desde 01/01/2026)'],
['Evolução salarial','R$ 1.100,00 (2021); R$ 1.240,00 (2022); R$ 1.350,00 (2023); R$ 1.451,00 (2024); R$ 1.550,00 (2025): reajustes anuais de pequena monta, sem mudança de cargo em mais de cinco anos'],
['Vínculos anteriores','Equipacar Peças e Tintas Ltda. — serviços gerais — 10/01/2020 a 05/12/2020 — R$ 552,00 a R$ 1.104,00'],
['Outros vínculos simultâneos','Nenhum registrado'],
]));
C.push(legend('Quadro 1 — Renda do Recorrente segundo a CTPS Digital (Doc. 1)'));
C.push(body('A renda registrada é de **R$ 1.653,00 mensais**, pouco acima de um salário mínimo (R$ 1.621,00 em 2026), em cargo operacional ocupado há mais de cinco anos, sem outro vínculo. É renda de subsistência, que não comporta o desembolso de preparo recursal sem prejuízo do sustento do Recorrente, o que atrai o art. 5º, LXXIV, da CF/88 e o art. 98 do CPC. A menção genérica da inicial a benefício previdenciário não altera esse quadro: a renda a considerar é a salarial acima comprovada.'));
C.push(body('Requer-se, portanto, a **concessão da gratuidade**, com dispensa do preparo (art. 99, § 7º, do CPC [VERIFICAR ANTES DE PROTOCOLAR]). Se o Colegiado entender necessária prova complementar (contracheque, declaração de imposto de renda, despesas ordinárias), requer-se **intimação prévia para complementação**, nos termos do art. 99, § 2º, e, em último caso, prazo para recolhimento do preparo sem deserção. A gratuidade também suspende a exigibilidade de eventual sucumbência recursal (art. 98, § 3º, do CPC [VERIFICAR ANTES DE PROTOCOLAR]).'));

C.push(H2('III — Delimitação do objeto do recurso'));
C.push(body('A inexistência da relação jurídica, o encerramento da conta e a confirmação da tutela já foram reconhecidos e **não são objeto deste recurso**. Devolve-se à Turma exclusivamente o **capítulo indenizatório**: (i) danos morais *in re ipsa* (R$ 8.000,00) e (ii) desvio produtivo (R$ 2.000,00), com pedido de arbitramento nos termos do tópico IV.3.'));
C.push(table([480,3500,2400,2646],['#','Fundamento da sentença (Id. 206519760)','Erro apontado','Atacado em'],[
['1','Falta de "prova de repercussão concreta" para o dano moral','Erro de direito: exige prova de dano presumido','IV.1.1 a IV.1.3'],
['2','"Consequência hipotética"; ausência de dívida/negativação ("NADA CONSTA")','Erro de direito e de fato: ônus invertido e prova produzida após a tutela','IV.1.4'],
['3','Vínculo "remontava a 2020"; ação só em 2026','Erro de direito: tempo de exposição agrava, não elide; ciência tardia','IV.1.4'],
['4','Desvio produtivo: "[DATA]" e ausência de prova','Erro de fato: desconsiderou prova nos autos','IV.2'],
]));
C.push(legend('Quadro 2 — Mapa dos fundamentos da sentença e das razões de reforma'));

C.push(H2('IV — Razões de reforma'));
C.push(H2('IV.1 — Do dano moral in re ipsa na abertura de conta sem consentimento'));
C.push(H2('IV.1.1 — O erro de direito: exigir prova de repercussão concreta para dano presumido'));
C.push(body('A sentença reconhece, simultaneamente, que (i) a Recorrida **não provou a contratação**, sequer apresentando "documento de identificação utilizado no procedimento", "registro biométrico", "fotografia (selfie)", "IP", "dispositivo" ou "geolocalização"; (ii) a Recorrida "reconheceu a inexistência de selfie de abertura e de registro biométrico"; e (iii) a irregularidade "pode caracterizar falha na prestação do serviço" (Id. 206519760, Págs. 239–240). Reconhecido o ilícito objetivo (art. 14 do CDC e Súmula 479/STJ), a sentença negou a reparação por não haver "demonstração de contratação de empréstimos", "prejuízo patrimonial", "cobrança de dívida" ou "inscrição" cadastral.'));
C.push(body('Essa exigência é o erro de direito que se impugna. **A lesão aqui não é a negativação nem o prejuízo material, que seriam danos diversos e ulteriores; é a própria apropriação e o tratamento dos dados pessoais do consumidor para constituir, em seu nome e à sua revelia, uma relação financeira registrada no cadastro oficial do sistema financeiro, mantida por seis anos.** Trata-se de violação de direitos da personalidade (art. 5º, X, da CF/88), de direito fundamental à proteção de dados (art. 5º, LXXIX, da CF/88) e de tratamento de dados sem base legal e sem segurança (arts. 42 e 46 da Lei 13.709/2018). Quem exige, para a reparação, a prova de "dívida" ou de "inscrição" pressupõe que só haveria dano se a fraude já tivesse produzido resultado, o que equivale a negar a tutela preventiva e a transferir ao consumidor o risco da atividade, em sentido contrário à Súmula 479/STJ.'));
C.push(H2('IV.1.2 — O que a Recorrida admitiu: ilícito na origem, sem lastro'));
C.push(body('A Recorrida **admite**, em manifestação complementar, que "não há selfie de abertura nem registro biométrico vinculado a este cadastro" (Id. 205739459, Pág. 225), e afirma que seus "subsídios" para a defesa "concentram-se no cumprimento da tutela de urgência e na ausência de negativação" (Id. 205727427, Pág. 160). Em outras palavras: **não tem documento técnico algum da abertura**, e a sua defesa se resume a invocar que o Recorrente não foi negativado, argumento que a sentença acolheu para negar a indenização, convertendo a lacuna probatória da Recorrida em fundamento para afastar o dano. A conta, segundo o Registrato, permanece **ativa** (Id. 202266801, Pág. 18) e seguiu assim até a sentença.'));
C.push(H2('IV.1.3 — Os parâmetros: REsp 2.201.694/SP (STJ) e sentença Antonieta × Dock (JEC/BA)'));
C.push(body('**a) REsp 2.201.694/SP (Doc. 2).** A Terceira Turma do STJ, por maioria (Rel. originário Min. Ricardo Villas Bôas Cueva; Rel. p/ acórdão Min. Nancy Andrighi; j. 05/08/2025; DJEN 15/08/2025), deu provimento ao recurso do consumidor e assentou, na ementa (item 4), que o gestor de banco de dados que disponibiliza indevidamente dados do cadastrado "deve responder objetivamente pelos danos morais causados ao cadastrado, **que são presumidos, diante da forte sensação de insegurança por ele experimentada**", fixando a indenização em **R$ 11.000,00** (Voto-vencedor, dispositivo). O caso tem objeto próprio (birô de crédito; disponibilização de dados a terceiros consulentes) e é invocado aqui como **parâmetro** em dois pontos: (i) a natureza **presumida** do dano decorrente do tratamento indevido de dados pessoais, independentemente de prejuízo patrimonial, ancorada na insegurança do titular; e (ii) a **ordem de grandeza** da compensação nessa espécie de lesão. A situação do Recorrente não é menos grave: seus dados foram usados para constituir relação financeira que ele desconhecia, registrada no CCS.'));
C.push(body('**b) Sentença no processo nº 0022386-55.2026.8.05.0080 (5ª Vara do Sistema dos Juizados de Feira de Santana/BA — Antonieta Freitas Mota × Dock Instituição de Pagamento S.A.) (Doc. 3).** Caso materialmente idêntico, do mesmo Tribunal: conta de pagamento aberta em nome da consumidora, com relacionamento ativo desde 02/06/2023, sem prova de contratação (ausência de contrato, aceite eletrônico, IP, dispositivo e biometria) e **sem negativação nem prejuízo material alegado**. A sentença, homologada pela Juíza de Direito, reconheceu "dano *in re ipsa*, decorrente da própria constituição e manutenção, à revelia da titular, de relacionamento inserido em cadastro oficial do sistema financeiro nacional, circunstância apta a gerar fundada sensação de insegurança e exposição a riscos que escapam ao controle da consumidora, tais como bloqueios, movimentações não reconhecidas e utilização indevida de seus dados pessoais, **dispensando-se a comprovação de prejuízo patrimonial específico**", e fixou **R$ 5.000,00**, com correção pelo IPCA e juros pela Selic. É decisão de primeiro grau, sem eficácia vinculante, trazida como parâmetro de razoabilidade e de coerência de julgamento em hipótese fática idêntica.'));
C.push(table([2600,2200,2000,2226],['Parâmetro','Natureza da lesão','Exigiu negativação?','Valor'],[
['REsp 2.201.694/SP (3ª T., STJ, 2025)','Dados pessoais disponibilizados indevidamente (dano presumido)','Não','R$ 11.000,00'],
['Proc. 0022386-55.2026.8.05.0080 (JEC Feira de Santana/BA, 2026)','Conta aberta sem consentimento, registrada no CCS (dano *in re ipsa*)','Não','R$ 5.000,00 (+ multa de R$ 300/dia pela obrigação de fazer)'],
['Pedido do Recorrente (inicial)','Conta aberta sem consentimento, ativa por seis anos','—','R$ 8.000,00 + R$ 2.000,00'],
]));
C.push(legend('Quadro 3 — Parâmetros de arbitramento'));
C.push(H2('IV.1.4 — A "consequência hipotética", o "NADA CONSTA" e o lapso de 2020 a 2026'));
C.push(body('**"Consequência hipotética".** A sentença afirma que a "possibilidade abstrata" de uso da conta para fraudes não é dano. Mas o risco é a consequência direta de existir, em nome do consumidor, uma conta ativa, aberta sem qualquer validação de identidade (a Recorrida admite que não há biometria nem selfie), de que ele não tinha ciência e sobre cuja movimentação não tinha controle. Esse estado de insegurança e de perda de controle sobre os próprios dados é precisamente o que o STJ reconhece como fundamento do dano presumido (item IV.1.3, "a") e o que a sentença Antonieta × Dock descreve. A Recorrida, que tem acesso exclusivo aos registros de acesso e movimentação da conta, não os juntou; e **a sentença já havia invertido o ônus da prova** (Id. 206519760, Pág. 239), de modo que cabia à Recorrida, e não ao consumidor, demonstrar a ausência de exposição, o que ela não fez.'));
C.push(body('**"NADA CONSTA".** O comprovante de "NADA CONSTA" e o "painel interno" de inibição do CPF são de **14/09/2026** (Id. 205727427, Págs. 157–159), isto é, produzidos **depois** da tutela de urgência deferida em 24/08/2026 (Id. 204098052, Págs. 147–148), que proibiu a negativação. Eles demonstram o cumprimento da ordem judicial, não a ausência de risco ou de exposição nos seis anos anteriores. A ausência de negativação em um dia específico não é circunstância "adicional" que afaste o dano: é o que a tutela de urgência visava garantir.'));
C.push(body('**O lapso entre 2020 e 2026.** A sentença extrai do tempo da conta (seis anos) a inexistência de repercussão. O raciocínio se inverte: (i) o Recorrente **só tomou ciência** da conta ao consultar o Registrato em 2026 (Id. 202266797, Pág. 2), e não há dever de monitorar periodicamente todas as instituições do sistema financeiro; ausência de reclamação durante o período em que ignorava a conta não é anuência nem convalida o ato; (ii) a nulidade não se convalida pelo decurso do tempo (art. 169 do CC), e a própria sentença declarou a inexistência da relação; (iii) cada ano de manutenção da conta ativa **prolonga** a exposição do consumidor, e a sentença Antonieta × Dock, com relacionamento de três anos, reconheceu o dano; aqui, são seis.'));
C.push(H2('IV.1.5 — Os precedentes de "mero aborrecimento" invocados pela Recorrida'));
C.push(body('A Recorrida invocou precedentes sobre cobrança indevida de fatura, bloqueio de cartão por inadimplemento e vício contratual (REsp 1.550.509/RJ, REsp 1.426.710, AgInt no REsp 1.650.402/SP, REsp 1.636.932/SP e REsp 714.611/PB — Id. 205727427, Págs. 163–167). Todos tratam de **inadimplemento ou erro operacional em relação contratual regularmente constituída**, em que o consumidor sabia da relação e discutia a execução. Aqui o ilícito é **anterior e mais grave**: a própria relação foi constituída sem manifestação de vontade, com o uso de dados pessoais do consumidor, o que atrai o regime do fato do serviço (art. 14 do CDC), da Súmula 479/STJ e da proteção de dados (LGPD, arts. 42 e 46; CF, art. 5º, LXXIX). Distinção fundamental, que a sentença não enfrentou.'));
C.push(H2('IV.1.6 — A pluralidade de ações não afasta o dano'));
C.push(body('A sentença não se apoiou nisso, mas, por cautela: o fato de o Recorrente ter ajuizado outras ações contra outras instituições não elide o dano causado por esta. Cada relação financeira fraudulenta é um ato autônomo, de uma instituição distinta, e a pluralidade decorre justamente da dimensão do vazamento de dados que atinge o consumidor. Não existe compensação entre ilícitos de fornecedores diversos nem vedação a demandar cada um deles pelo que lhe cabe.'));
C.push(cons('a sentença exigiu prova de consequência concreta para dano presumido e tratou como hipotética a exposição que decorre da própria conta; impõe-se a reforma do capítulo e a condenação da Recorrida em danos morais.'));

C.push(H2('IV.2 — Do desvio produtivo do consumidor'));
C.push(body('A sentença rejeitou o pedido de R$ 2.000,00 por entender que a narrativa de tentativas administrativas traz "marcador não individualizado de data — [DATA]" e que não há "demonstração suficiente de sucessivas e frustradas tentativas de resolução". Duas observações. **Primeira**, o marcador "[DATA]" é lapso redacional em uma frase da inicial e não apaga a circunstância fática: o Recorrente descobriu a conta, buscou documentos, enviou requerimento administrativo à Recorrida, **juntado aos autos** (e-mail de 07/08/2026 a oi@picpay.com, com a procuração, Id. 203922661, Págs. 143–146), sem resposta ou impugnação da Recorrida quanto ao seu recebimento, e compareceu à audiência de 17/09/2026 (Id. 205798377, Págs. 234–235). **Segunda**, a sentença desconsiderou que a Súmula 30 da Turma Recursal do TJBA, invocada na inicial (Id. 202266797, Pág. 8), reconhece que a usurpação do tempo do consumidor na tentativa de resolver problema a que não deu causa pode caracterizar desvio produtivo "a depender das circunstâncias do caso concreto" [VERIFICAR ANTES DE PROTOCOLAR a redação da súmula]; entre essas circunstâncias, a de que a Recorrida **não dispunha de documento algum da abertura** e, ainda assim, manteve a conta por seis anos.'));
C.push(body('Ainda que o Colegiado entenda insuficiente a prova para a indenização autônoma, requer que o tempo e os esforços despendidos sejam considerados **na quantificação do dano moral** (IV.3), como circunstância agravante.'));

C.push(H2('IV.3 — Do arbitramento dos danos morais'));
C.push(body('Os valores pleiteados na inicial são **R$ 8.000,00** (danos morais) e **R$ 2.000,00** (desvio produtivo), totalizando **R$ 10.000,00**, e são mantidos, por serem proporcionais à extensão do dano (art. 944 do CC, invocado pela própria Recorrida — Id. 205727427, Pág. 168). Confrontados com os parâmetros do Quadro 3, situam-se **entre** o valor fixado em primeiro grau num caso idêntico (R$ 5.000,00) e o fixado pelo STJ num caso de dano presumido por tratamento indevido de dados (R$ 11.000,00). Pesam na quantificação: (i) a gravidade do ilícito, a abertura de conta sem **nenhum** elemento de validação de identidade (admitido pela Recorrida); (ii) o prazo de **seis anos** de manutenção do vínculo; (iii) o porte da Recorrida, instituição financeira de alcance nacional, com a finalidade pedagógica da indenização; (iv) o tempo despendido pelo Recorrente; e (v) a ausência de prova de qualquer diligência da Recorrida para identificar o titular.'));
C.push(body('Caso a Turma não acolha os valores integrais, requer-se o **arbitramento pelo próprio Colegiado**, dentro do limite do pedido (R$ 10.000,00), em valor **não inferior a R$ 5.000,00**, que é o piso fixado em primeiro grau para situação idêntica. Sobre o valor incidem juros de mora desde o evento danoso (Súmula 54/STJ) ou, subsidiariamente, desde a citação, e correção monetária desde o arbitramento (Súmula 362/STJ), observado, para os períodos a partir de 30/08/2024, o art. 406 do CC, com a redação da Lei 14.905/2024.'));

C.push(H2('V — Prequestionamento'));
C.push(body('Para fins de eventual Recurso Extraordinário (art. 102, III, da CF/88) e de pedido de uniformização de jurisprudência, ficam prequestionados os arts. 5º, X, XXXV, LXXIV e LXXIX, da CF/88; os arts. 6º, VIII, e 14 do CDC; a Súmula 479/STJ; os arts. 42 e 46 da Lei 13.709/2018; e os arts. 98 e 99 do CPC. Registra-se a divergência, quanto ao dano presumido na abertura de conta sem consentimento e sem negativação, entre a sentença de Feira de Santana/BA (Doc. 3), que o reconhece, e decisões que o negam, a justificar, se necessário, a uniformização.'));

C.push(H2('VI — Pedidos'));
C.push(body('Ante o exposto, requer o Recorrente:'));
[
'a)\tO **recebimento do recurso** com a **concessão da gratuidade da justiça**, dispensado o preparo (art. 42, § 1º, da Lei 9.099/95; arts. 98 e 99 do CPC), à vista da declaração de hipossuficiência e da CTPS Digital (Doc. 1); subsidiariamente, a intimação para complementação da prova (art. 99, § 2º, do CPC) e, em último caso, prazo para recolhimento, sem deserção;',
'b)\tO **conhecimento e provimento do recurso** para reformar o capítulo indenizatório da sentença de Id. 206519760 e **condenar a Recorrida** ao pagamento de **R$ 8.000,00 a título de danos morais** e **R$ 2.000,00 a título de desvio produtivo**, valores da inicial, com juros e correção na forma do tópico IV.3;',
'c)\tSubsidiariamente, o **arbitramento judicial** dos danos morais pela Turma, em valor **não inferior a R$ 5.000,00**, dentro do limite do pedido, tomando-se por parâmetro o REsp 2.201.694/SP (R$ 11.000,00) e a sentença do processo nº 0022386-55.2026.8.05.0080 (R$ 5.000,00), com a consideração do tempo despendido (tópico IV.2) na quantificação;',
'd)\tA manutenção dos capítulos já favoráveis (declaração de inexistência, encerramento da conta e confirmação da tutela de urgência), que não são objeto deste recurso;',
'e)\tA condenação da Recorrida nas custas e honorários de sucumbência recursal, se vencida (art. 55 da Lei 9.099/95);',
'f)\tQue as intimações sejam feitas em nome do advogado **CLEYTON DA SILVA BARBOSA, OAB/MS 17.311 e OAB/BA 92.148**.'
].forEach(t=>C.push(alinea(t)));
C.push(plain('**Documentos anexos:** Doc. 1 — CTPS Digital do Recorrente (Dataprev, 29/07/2026); Doc. 2 — Acórdão do REsp 2.201.694/SP (STJ); Doc. 3 — Sentença do processo nº 0022386-55.2026.8.05.0080 (5ª VSJ de Feira de Santana/BA).',{align:AlignmentType.JUSTIFIED,after:200}));
C.push(plain('Nestes termos, pede deferimento.',{align:AlignmentType.LEFT,indent:{firstLine:708},after:60}));
C.push(plain('Jequié/BA, ___ de outubro de 2026.',{align:AlignmentType.LEFT,indent:{firstLine:708},after:400}));
C.push(plain('CLEYTON DA SILVA BARBOSA',{align:AlignmentType.CENTER,after:0,bold:true}));
C.push(plain('OAB/MS 17.311 — OAB/BA 92.148',{align:AlignmentType.CENTER,after:0}));
const doc=new Document({styles:{default:{document:{run:{font:'Arial',size:24}}}},
 sections:[{properties:{page:{size:{width:11906,height:16838},margin:{top:1701,bottom:1134,left:1701,right:1134}}},
 footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:ID+' — Recurso Inominado — página ',size:18,font:'Arial'}),new TextRun({children:[PageNumber.CURRENT],size:18,font:'Arial'}),new TextRun({text:' de ',size:18,font:'Arial'}),new TextRun({children:[PageNumber.TOTAL_PAGES],size:18,font:'Arial'})]})]})},
 children:C}]});
Packer.toBuffer(doc).then(b=>{fs.writeFileSync('recurso_inominado_conta_fraudulenta.docx',b);console.log('ok',b.length)});
